// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.0
// source: betting.proto

package betting

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BettingService_CreateSetting_FullMethodName           = "/betting.BettingService/CreateSetting"
	BettingService_UpdateSetting_FullMethodName           = "/betting.BettingService/UpdateSetting"
	BettingService_GetSettingsByID_FullMethodName         = "/betting.BettingService/GetSettingsByID"
	BettingService_GetAllSettings_FullMethodName          = "/betting.BettingService/GetAllSettings"
	BettingService_CancelBet_FullMethodName               = "/betting.BettingService/CancelBet"
	BettingService_PlaceBet_FullMethodName                = "/betting.BettingService/PlaceBet"
	BettingService_PlaceCasinoBet_FullMethodName          = "/betting.BettingService/PlaceCasinoBet"
	BettingService_PlaceVirtualBet_FullMethodName         = "/betting.BettingService/PlaceVirtualBet"
	BettingService_SettleCasinoBet_FullMethodName         = "/betting.BettingService/SettleCasinoBet"
	BettingService_CloseCasinoRound_FullMethodName        = "/betting.BettingService/CloseCasinoRound"
	BettingService_SettleVirtualBet_FullMethodName        = "/betting.BettingService/SettleVirtualBet"
	BettingService_CancelCasinoBet_FullMethodName         = "/betting.BettingService/CancelCasinoBet"
	BettingService_BetHistory_FullMethodName              = "/betting.BettingService/BetHistory"
	BettingService_SimulatedBetHistory_FullMethodName     = "/betting.BettingService/SimulatedBetHistory"
	BettingService_FindBet_FullMethodName                 = "/betting.BettingService/FindBet"
	BettingService_UpdateBet_FullMethodName               = "/betting.BettingService/UpdateBet"
	BettingService_GetProbabilityFromBetID_FullMethodName = "/betting.BettingService/GetProbabilityFromBetID"
	BettingService_GetCoupon_FullMethodName               = "/betting.BettingService/GetCoupon"
	BettingService_GamingActivity_FullMethodName          = "/betting.BettingService/GamingActivity"
	BettingService_GetVirtualBet_FullMethodName           = "/betting.BettingService/GetVirtualBet"
	BettingService_GetVirtualBets_FullMethodName          = "/betting.BettingService/GetVirtualBets"
	BettingService_CashoutRequest_FullMethodName          = "/betting.BettingService/CashoutRequest"
	BettingService_GetRetailBets_FullMethodName           = "/betting.BettingService/GetRetailBets"
	BettingService_GetRetailVBets_FullMethodName          = "/betting.BettingService/GetRetailVBets"
	BettingService_GetSalesReport_FullMethodName          = "/betting.BettingService/GetSalesReport"
	BettingService_GetShopUserCommissions_FullMethodName  = "/betting.BettingService/GetShopUserCommissions"
	BettingService_GetTotalSalesReport_FullMethodName     = "/betting.BettingService/GetTotalSalesReport"
	BettingService_DeletePlayerData_FullMethodName        = "/betting.BettingService/DeletePlayerData"
	BettingService_GetCommissions_FullMethodName          = "/betting.BettingService/GetCommissions"
	BettingService_GetAgentTotals_FullMethodName          = "/betting.BettingService/GetAgentTotals"
	BettingService_TicketsReport_FullMethodName           = "/betting.BettingService/TicketsReport"
	BettingService_TaxReport_FullMethodName               = "/betting.BettingService/TaxReport"
	BettingService_GetCodeHubTickets_FullMethodName       = "/betting.BettingService/GetCodeHubTickets"
	BettingService_PayoutTicket_FullMethodName            = "/betting.BettingService/PayoutTicket"
	BettingService_SaveSettings_FullMethodName            = "/betting.BettingService/SaveSettings"
	BettingService_SaveRiskSettings_FullMethodName        = "/betting.BettingService/SaveRiskSettings"
	BettingService_SaveUserRiskSettings_FullMethodName    = "/betting.BettingService/SaveUserRiskSettings"
	BettingService_GetSettings_FullMethodName             = "/betting.BettingService/GetSettings"
	BettingService_GetGlobalVariables_FullMethodName      = "/betting.BettingService/GetGlobalVariables"
	BettingService_GetUserRiskSettings_FullMethodName     = "/betting.BettingService/GetUserRiskSettings"
	BettingService_ValidateSelections_FullMethodName      = "/betting.BettingService/ValidateSelections"
	BettingService_ManualSettlement_FullMethodName        = "/betting.BettingService/ManualSettlement"
)

// BettingServiceClient is the client API for BettingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BettingServiceClient interface {
	CreateSetting(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*SettingsResponse, error)
	UpdateSetting(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*SettingsResponse, error)
	GetSettingsByID(ctx context.Context, in *SettingsById, opts ...grpc.CallOption) (*SettingsResponse, error)
	GetAllSettings(ctx context.Context, in *GetAll, opts ...grpc.CallOption) (*AllSettingsResponse, error)
	CancelBet(ctx context.Context, in *BookingCode, opts ...grpc.CallOption) (*CommonResponseObj, error)
	PlaceBet(ctx context.Context, in *PlaceBetRequest, opts ...grpc.CallOption) (*PlaceBetResponse, error)
	PlaceCasinoBet(ctx context.Context, in *PlaceCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error)
	PlaceVirtualBet(ctx context.Context, in *PlaceVirtualBetRequest, opts ...grpc.CallOption) (*PlaceVirtualBetResponse, error)
	SettleCasinoBet(ctx context.Context, in *SettleCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error)
	CloseCasinoRound(ctx context.Context, in *SettleCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error)
	SettleVirtualBet(ctx context.Context, in *SettleVirtualBetRequest, opts ...grpc.CallOption) (*SettleVirtualBetResponse, error)
	CancelCasinoBet(ctx context.Context, in *RollbackCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error)
	BetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*BetHistoryResponse, error)
	SimulatedBetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*BetHistoryResponse, error)
	FindBet(ctx context.Context, in *FindBetRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	UpdateBet(ctx context.Context, in *UpdateBetRequest, opts ...grpc.CallOption) (*UpdateBetResponse, error)
	GetProbabilityFromBetID(ctx context.Context, in *BetID, opts ...grpc.CallOption) (*Probability, error)
	GetCoupon(ctx context.Context, in *FindBetRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GamingActivity(ctx context.Context, in *GamingActivityRequest, opts ...grpc.CallOption) (*GamingActivityResponse, error)
	GetVirtualBet(ctx context.Context, in *GetVirtualBetRequest, opts ...grpc.CallOption) (*GetVirtualBetResponse, error)
	GetVirtualBets(ctx context.Context, in *GetVirtualBetsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	CashoutRequest(ctx context.Context, in *ProcessCashoutRequest, opts ...grpc.CallOption) (*ProcessCashoutResponse, error)
	GetRetailBets(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetRetailVBets(ctx context.Context, in *GetVirtualBetsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetSalesReport(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetShopUserCommissions(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetTotalSalesReport(ctx context.Context, in *NetworkSalesRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	DeletePlayerData(ctx context.Context, in *SettingsById, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetCommissions(ctx context.Context, in *GetCommissionsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetAgentTotals(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	TicketsReport(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	TaxReport(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetCodeHubTickets(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	PayoutTicket(ctx context.Context, in *BetID, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SaveSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SaveRiskSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SaveUserRiskSettings(ctx context.Context, in *UserRiskSettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	GetGlobalVariables(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetUserRiskSettings(ctx context.Context, in *GetRiskSettingRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	ValidateSelections(ctx context.Context, in *ValidateSelectionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	ManualSettlement(ctx context.Context, in *ManualSettlementRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
}

type bettingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBettingServiceClient(cc grpc.ClientConnInterface) BettingServiceClient {
	return &bettingServiceClient{cc}
}

func (c *bettingServiceClient) CreateSetting(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*SettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, BettingService_CreateSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) UpdateSetting(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*SettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, BettingService_UpdateSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetSettingsByID(ctx context.Context, in *SettingsById, opts ...grpc.CallOption) (*SettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, BettingService_GetSettingsByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetAllSettings(ctx context.Context, in *GetAll, opts ...grpc.CallOption) (*AllSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllSettingsResponse)
	err := c.cc.Invoke(ctx, BettingService_GetAllSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) CancelBet(ctx context.Context, in *BookingCode, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_CancelBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) PlaceBet(ctx context.Context, in *PlaceBetRequest, opts ...grpc.CallOption) (*PlaceBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceBetResponse)
	err := c.cc.Invoke(ctx, BettingService_PlaceBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) PlaceCasinoBet(ctx context.Context, in *PlaceCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceCasinoBetResponse)
	err := c.cc.Invoke(ctx, BettingService_PlaceCasinoBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) PlaceVirtualBet(ctx context.Context, in *PlaceVirtualBetRequest, opts ...grpc.CallOption) (*PlaceVirtualBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceVirtualBetResponse)
	err := c.cc.Invoke(ctx, BettingService_PlaceVirtualBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SettleCasinoBet(ctx context.Context, in *SettleCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceCasinoBetResponse)
	err := c.cc.Invoke(ctx, BettingService_SettleCasinoBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) CloseCasinoRound(ctx context.Context, in *SettleCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceCasinoBetResponse)
	err := c.cc.Invoke(ctx, BettingService_CloseCasinoRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SettleVirtualBet(ctx context.Context, in *SettleVirtualBetRequest, opts ...grpc.CallOption) (*SettleVirtualBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleVirtualBetResponse)
	err := c.cc.Invoke(ctx, BettingService_SettleVirtualBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) CancelCasinoBet(ctx context.Context, in *RollbackCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceCasinoBetResponse)
	err := c.cc.Invoke(ctx, BettingService_CancelCasinoBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) BetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*BetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetHistoryResponse)
	err := c.cc.Invoke(ctx, BettingService_BetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SimulatedBetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*BetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetHistoryResponse)
	err := c.cc.Invoke(ctx, BettingService_SimulatedBetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) FindBet(ctx context.Context, in *FindBetRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_FindBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) UpdateBet(ctx context.Context, in *UpdateBetRequest, opts ...grpc.CallOption) (*UpdateBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBetResponse)
	err := c.cc.Invoke(ctx, BettingService_UpdateBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetProbabilityFromBetID(ctx context.Context, in *BetID, opts ...grpc.CallOption) (*Probability, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Probability)
	err := c.cc.Invoke(ctx, BettingService_GetProbabilityFromBetID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetCoupon(ctx context.Context, in *FindBetRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_GetCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GamingActivity(ctx context.Context, in *GamingActivityRequest, opts ...grpc.CallOption) (*GamingActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GamingActivityResponse)
	err := c.cc.Invoke(ctx, BettingService_GamingActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetVirtualBet(ctx context.Context, in *GetVirtualBetRequest, opts ...grpc.CallOption) (*GetVirtualBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVirtualBetResponse)
	err := c.cc.Invoke(ctx, BettingService_GetVirtualBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetVirtualBets(ctx context.Context, in *GetVirtualBetsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_GetVirtualBets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) CashoutRequest(ctx context.Context, in *ProcessCashoutRequest, opts ...grpc.CallOption) (*ProcessCashoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessCashoutResponse)
	err := c.cc.Invoke(ctx, BettingService_CashoutRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetRetailBets(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_GetRetailBets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetRetailVBets(ctx context.Context, in *GetVirtualBetsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_GetRetailVBets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetSalesReport(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_GetSalesReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetShopUserCommissions(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_GetShopUserCommissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetTotalSalesReport(ctx context.Context, in *NetworkSalesRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_GetTotalSalesReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) DeletePlayerData(ctx context.Context, in *SettingsById, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_DeletePlayerData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetCommissions(ctx context.Context, in *GetCommissionsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_GetCommissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetAgentTotals(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, BettingService_GetAgentTotals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) TicketsReport(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_TicketsReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) TaxReport(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_TaxReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetCodeHubTickets(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_GetCodeHubTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) PayoutTicket(ctx context.Context, in *BetID, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_PayoutTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SaveSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_SaveSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SaveRiskSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_SaveRiskSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SaveUserRiskSettings(ctx context.Context, in *UserRiskSettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_SaveUserRiskSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, BettingService_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetGlobalVariables(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_GetGlobalVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetUserRiskSettings(ctx context.Context, in *GetRiskSettingRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_GetUserRiskSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) ValidateSelections(ctx context.Context, in *ValidateSelectionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_ValidateSelections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) ManualSettlement(ctx context.Context, in *ManualSettlementRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, BettingService_ManualSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BettingServiceServer is the server API for BettingService service.
// All implementations must embed UnimplementedBettingServiceServer
// for forward compatibility.
type BettingServiceServer interface {
	CreateSetting(context.Context, *Settings) (*SettingsResponse, error)
	UpdateSetting(context.Context, *Settings) (*SettingsResponse, error)
	GetSettingsByID(context.Context, *SettingsById) (*SettingsResponse, error)
	GetAllSettings(context.Context, *GetAll) (*AllSettingsResponse, error)
	CancelBet(context.Context, *BookingCode) (*CommonResponseObj, error)
	PlaceBet(context.Context, *PlaceBetRequest) (*PlaceBetResponse, error)
	PlaceCasinoBet(context.Context, *PlaceCasinoBetRequest) (*PlaceCasinoBetResponse, error)
	PlaceVirtualBet(context.Context, *PlaceVirtualBetRequest) (*PlaceVirtualBetResponse, error)
	SettleCasinoBet(context.Context, *SettleCasinoBetRequest) (*PlaceCasinoBetResponse, error)
	CloseCasinoRound(context.Context, *SettleCasinoBetRequest) (*PlaceCasinoBetResponse, error)
	SettleVirtualBet(context.Context, *SettleVirtualBetRequest) (*SettleVirtualBetResponse, error)
	CancelCasinoBet(context.Context, *RollbackCasinoBetRequest) (*PlaceCasinoBetResponse, error)
	BetHistory(context.Context, *BetHistoryRequest) (*BetHistoryResponse, error)
	SimulatedBetHistory(context.Context, *BetHistoryRequest) (*BetHistoryResponse, error)
	FindBet(context.Context, *FindBetRequest) (*CommonResponseObj, error)
	UpdateBet(context.Context, *UpdateBetRequest) (*UpdateBetResponse, error)
	GetProbabilityFromBetID(context.Context, *BetID) (*Probability, error)
	GetCoupon(context.Context, *FindBetRequest) (*CommonResponseObj, error)
	GamingActivity(context.Context, *GamingActivityRequest) (*GamingActivityResponse, error)
	GetVirtualBet(context.Context, *GetVirtualBetRequest) (*GetVirtualBetResponse, error)
	GetVirtualBets(context.Context, *GetVirtualBetsRequest) (*CommonResponseObj, error)
	CashoutRequest(context.Context, *ProcessCashoutRequest) (*ProcessCashoutResponse, error)
	GetRetailBets(context.Context, *BetHistoryRequest) (*CommonResponseObj, error)
	GetRetailVBets(context.Context, *GetVirtualBetsRequest) (*CommonResponseObj, error)
	GetSalesReport(context.Context, *SalesReportRequest) (*CommonResponseObj, error)
	GetShopUserCommissions(context.Context, *SalesReportRequest) (*CommonResponseObj, error)
	GetTotalSalesReport(context.Context, *NetworkSalesRequest) (*CommonResponseObj, error)
	DeletePlayerData(context.Context, *SettingsById) (*CommonResponseObj, error)
	GetCommissions(context.Context, *GetCommissionsRequest) (*CommonResponseObj, error)
	GetAgentTotals(context.Context, *SalesReportRequest) (*CommonResponseArray, error)
	TicketsReport(context.Context, *GetTicketsRequest) (*CommonResponseObj, error)
	TaxReport(context.Context, *GetTicketsRequest) (*CommonResponseObj, error)
	GetCodeHubTickets(context.Context, *GetTicketsRequest) (*CommonResponseObj, error)
	PayoutTicket(context.Context, *BetID) (*CommonResponseObj, error)
	SaveSettings(context.Context, *SettingsRequest) (*CommonResponseObj, error)
	SaveRiskSettings(context.Context, *SettingsRequest) (*CommonResponseObj, error)
	SaveUserRiskSettings(context.Context, *UserRiskSettingsRequest) (*CommonResponseObj, error)
	GetSettings(context.Context, *GetSettingsRequest) (*CommonResponseArray, error)
	GetGlobalVariables(context.Context, *GetSettingsRequest) (*CommonResponseObj, error)
	GetUserRiskSettings(context.Context, *GetRiskSettingRequest) (*CommonResponseObj, error)
	ValidateSelections(context.Context, *ValidateSelectionRequest) (*CommonResponseObj, error)
	ManualSettlement(context.Context, *ManualSettlementRequest) (*CommonResponseObj, error)
	mustEmbedUnimplementedBettingServiceServer()
}

// UnimplementedBettingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBettingServiceServer struct{}

func (UnimplementedBettingServiceServer) CreateSetting(context.Context, *Settings) (*SettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSetting not implemented")
}
func (UnimplementedBettingServiceServer) UpdateSetting(context.Context, *Settings) (*SettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSetting not implemented")
}
func (UnimplementedBettingServiceServer) GetSettingsByID(context.Context, *SettingsById) (*SettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettingsByID not implemented")
}
func (UnimplementedBettingServiceServer) GetAllSettings(context.Context, *GetAll) (*AllSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSettings not implemented")
}
func (UnimplementedBettingServiceServer) CancelBet(context.Context, *BookingCode) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBet not implemented")
}
func (UnimplementedBettingServiceServer) PlaceBet(context.Context, *PlaceBetRequest) (*PlaceBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceBet not implemented")
}
func (UnimplementedBettingServiceServer) PlaceCasinoBet(context.Context, *PlaceCasinoBetRequest) (*PlaceCasinoBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceCasinoBet not implemented")
}
func (UnimplementedBettingServiceServer) PlaceVirtualBet(context.Context, *PlaceVirtualBetRequest) (*PlaceVirtualBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceVirtualBet not implemented")
}
func (UnimplementedBettingServiceServer) SettleCasinoBet(context.Context, *SettleCasinoBetRequest) (*PlaceCasinoBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleCasinoBet not implemented")
}
func (UnimplementedBettingServiceServer) CloseCasinoRound(context.Context, *SettleCasinoBetRequest) (*PlaceCasinoBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseCasinoRound not implemented")
}
func (UnimplementedBettingServiceServer) SettleVirtualBet(context.Context, *SettleVirtualBetRequest) (*SettleVirtualBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleVirtualBet not implemented")
}
func (UnimplementedBettingServiceServer) CancelCasinoBet(context.Context, *RollbackCasinoBetRequest) (*PlaceCasinoBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelCasinoBet not implemented")
}
func (UnimplementedBettingServiceServer) BetHistory(context.Context, *BetHistoryRequest) (*BetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BetHistory not implemented")
}
func (UnimplementedBettingServiceServer) SimulatedBetHistory(context.Context, *BetHistoryRequest) (*BetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SimulatedBetHistory not implemented")
}
func (UnimplementedBettingServiceServer) FindBet(context.Context, *FindBetRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method FindBet not implemented")
}
func (UnimplementedBettingServiceServer) UpdateBet(context.Context, *UpdateBetRequest) (*UpdateBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBet not implemented")
}
func (UnimplementedBettingServiceServer) GetProbabilityFromBetID(context.Context, *BetID) (*Probability, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProbabilityFromBetID not implemented")
}
func (UnimplementedBettingServiceServer) GetCoupon(context.Context, *FindBetRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoupon not implemented")
}
func (UnimplementedBettingServiceServer) GamingActivity(context.Context, *GamingActivityRequest) (*GamingActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GamingActivity not implemented")
}
func (UnimplementedBettingServiceServer) GetVirtualBet(context.Context, *GetVirtualBetRequest) (*GetVirtualBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVirtualBet not implemented")
}
func (UnimplementedBettingServiceServer) GetVirtualBets(context.Context, *GetVirtualBetsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVirtualBets not implemented")
}
func (UnimplementedBettingServiceServer) CashoutRequest(context.Context, *ProcessCashoutRequest) (*ProcessCashoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CashoutRequest not implemented")
}
func (UnimplementedBettingServiceServer) GetRetailBets(context.Context, *BetHistoryRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRetailBets not implemented")
}
func (UnimplementedBettingServiceServer) GetRetailVBets(context.Context, *GetVirtualBetsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRetailVBets not implemented")
}
func (UnimplementedBettingServiceServer) GetSalesReport(context.Context, *SalesReportRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSalesReport not implemented")
}
func (UnimplementedBettingServiceServer) GetShopUserCommissions(context.Context, *SalesReportRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShopUserCommissions not implemented")
}
func (UnimplementedBettingServiceServer) GetTotalSalesReport(context.Context, *NetworkSalesRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTotalSalesReport not implemented")
}
func (UnimplementedBettingServiceServer) DeletePlayerData(context.Context, *SettingsById) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlayerData not implemented")
}
func (UnimplementedBettingServiceServer) GetCommissions(context.Context, *GetCommissionsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommissions not implemented")
}
func (UnimplementedBettingServiceServer) GetAgentTotals(context.Context, *SalesReportRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentTotals not implemented")
}
func (UnimplementedBettingServiceServer) TicketsReport(context.Context, *GetTicketsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method TicketsReport not implemented")
}
func (UnimplementedBettingServiceServer) TaxReport(context.Context, *GetTicketsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method TaxReport not implemented")
}
func (UnimplementedBettingServiceServer) GetCodeHubTickets(context.Context, *GetTicketsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCodeHubTickets not implemented")
}
func (UnimplementedBettingServiceServer) PayoutTicket(context.Context, *BetID) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method PayoutTicket not implemented")
}
func (UnimplementedBettingServiceServer) SaveSettings(context.Context, *SettingsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSettings not implemented")
}
func (UnimplementedBettingServiceServer) SaveRiskSettings(context.Context, *SettingsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveRiskSettings not implemented")
}
func (UnimplementedBettingServiceServer) SaveUserRiskSettings(context.Context, *UserRiskSettingsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveUserRiskSettings not implemented")
}
func (UnimplementedBettingServiceServer) GetSettings(context.Context, *GetSettingsRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedBettingServiceServer) GetGlobalVariables(context.Context, *GetSettingsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalVariables not implemented")
}
func (UnimplementedBettingServiceServer) GetUserRiskSettings(context.Context, *GetRiskSettingRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRiskSettings not implemented")
}
func (UnimplementedBettingServiceServer) ValidateSelections(context.Context, *ValidateSelectionRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateSelections not implemented")
}
func (UnimplementedBettingServiceServer) ManualSettlement(context.Context, *ManualSettlementRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method ManualSettlement not implemented")
}
func (UnimplementedBettingServiceServer) mustEmbedUnimplementedBettingServiceServer() {}
func (UnimplementedBettingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBettingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BettingServiceServer will
// result in compilation errors.
type UnsafeBettingServiceServer interface {
	mustEmbedUnimplementedBettingServiceServer()
}

func RegisterBettingServiceServer(s grpc.ServiceRegistrar, srv BettingServiceServer) {
	// If the following call panics, it indicates UnimplementedBettingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BettingService_ServiceDesc, srv)
}

func _BettingService_CreateSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Settings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CreateSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_CreateSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CreateSetting(ctx, req.(*Settings))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_UpdateSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Settings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).UpdateSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_UpdateSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).UpdateSetting(ctx, req.(*Settings))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetSettingsByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetSettingsByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetSettingsByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetSettingsByID(ctx, req.(*SettingsById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetAllSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAll)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetAllSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetAllSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetAllSettings(ctx, req.(*GetAll))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_CancelBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CancelBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_CancelBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CancelBet(ctx, req.(*BookingCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_PlaceBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).PlaceBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_PlaceBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).PlaceBet(ctx, req.(*PlaceBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_PlaceCasinoBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceCasinoBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).PlaceCasinoBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_PlaceCasinoBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).PlaceCasinoBet(ctx, req.(*PlaceCasinoBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_PlaceVirtualBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceVirtualBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).PlaceVirtualBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_PlaceVirtualBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).PlaceVirtualBet(ctx, req.(*PlaceVirtualBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SettleCasinoBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleCasinoBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SettleCasinoBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_SettleCasinoBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SettleCasinoBet(ctx, req.(*SettleCasinoBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_CloseCasinoRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleCasinoBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CloseCasinoRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_CloseCasinoRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CloseCasinoRound(ctx, req.(*SettleCasinoBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SettleVirtualBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleVirtualBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SettleVirtualBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_SettleVirtualBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SettleVirtualBet(ctx, req.(*SettleVirtualBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_CancelCasinoBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackCasinoBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CancelCasinoBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_CancelCasinoBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CancelCasinoBet(ctx, req.(*RollbackCasinoBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_BetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).BetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_BetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).BetHistory(ctx, req.(*BetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SimulatedBetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SimulatedBetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_SimulatedBetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SimulatedBetHistory(ctx, req.(*BetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_FindBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).FindBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_FindBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).FindBet(ctx, req.(*FindBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_UpdateBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).UpdateBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_UpdateBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).UpdateBet(ctx, req.(*UpdateBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetProbabilityFromBetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetProbabilityFromBetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetProbabilityFromBetID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetProbabilityFromBetID(ctx, req.(*BetID))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetCoupon(ctx, req.(*FindBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GamingActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GamingActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GamingActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GamingActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GamingActivity(ctx, req.(*GamingActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetVirtualBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirtualBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetVirtualBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetVirtualBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetVirtualBet(ctx, req.(*GetVirtualBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetVirtualBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirtualBetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetVirtualBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetVirtualBets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetVirtualBets(ctx, req.(*GetVirtualBetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_CashoutRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessCashoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CashoutRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_CashoutRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CashoutRequest(ctx, req.(*ProcessCashoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetRetailBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetRetailBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetRetailBets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetRetailBets(ctx, req.(*BetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetRetailVBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirtualBetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetRetailVBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetRetailVBets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetRetailVBets(ctx, req.(*GetVirtualBetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetSalesReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetSalesReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetSalesReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetSalesReport(ctx, req.(*SalesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetShopUserCommissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetShopUserCommissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetShopUserCommissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetShopUserCommissions(ctx, req.(*SalesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetTotalSalesReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkSalesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetTotalSalesReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetTotalSalesReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetTotalSalesReport(ctx, req.(*NetworkSalesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_DeletePlayerData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).DeletePlayerData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_DeletePlayerData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).DeletePlayerData(ctx, req.(*SettingsById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetCommissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetCommissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetCommissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetCommissions(ctx, req.(*GetCommissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetAgentTotals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetAgentTotals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetAgentTotals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetAgentTotals(ctx, req.(*SalesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_TicketsReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).TicketsReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_TicketsReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).TicketsReport(ctx, req.(*GetTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_TaxReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).TaxReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_TaxReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).TaxReport(ctx, req.(*GetTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetCodeHubTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetCodeHubTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetCodeHubTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetCodeHubTickets(ctx, req.(*GetTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_PayoutTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).PayoutTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_PayoutTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).PayoutTicket(ctx, req.(*BetID))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SaveSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SaveSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_SaveSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SaveSettings(ctx, req.(*SettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SaveRiskSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SaveRiskSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_SaveRiskSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SaveRiskSettings(ctx, req.(*SettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SaveUserRiskSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRiskSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SaveUserRiskSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_SaveUserRiskSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SaveUserRiskSettings(ctx, req.(*UserRiskSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetGlobalVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetGlobalVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetGlobalVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetGlobalVariables(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetUserRiskSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiskSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetUserRiskSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetUserRiskSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetUserRiskSettings(ctx, req.(*GetRiskSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_ValidateSelections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).ValidateSelections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_ValidateSelections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).ValidateSelections(ctx, req.(*ValidateSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_ManualSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManualSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).ManualSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_ManualSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).ManualSettlement(ctx, req.(*ManualSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BettingService_ServiceDesc is the grpc.ServiceDesc for BettingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BettingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "betting.BettingService",
	HandlerType: (*BettingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSetting",
			Handler:    _BettingService_CreateSetting_Handler,
		},
		{
			MethodName: "UpdateSetting",
			Handler:    _BettingService_UpdateSetting_Handler,
		},
		{
			MethodName: "GetSettingsByID",
			Handler:    _BettingService_GetSettingsByID_Handler,
		},
		{
			MethodName: "GetAllSettings",
			Handler:    _BettingService_GetAllSettings_Handler,
		},
		{
			MethodName: "CancelBet",
			Handler:    _BettingService_CancelBet_Handler,
		},
		{
			MethodName: "PlaceBet",
			Handler:    _BettingService_PlaceBet_Handler,
		},
		{
			MethodName: "PlaceCasinoBet",
			Handler:    _BettingService_PlaceCasinoBet_Handler,
		},
		{
			MethodName: "PlaceVirtualBet",
			Handler:    _BettingService_PlaceVirtualBet_Handler,
		},
		{
			MethodName: "SettleCasinoBet",
			Handler:    _BettingService_SettleCasinoBet_Handler,
		},
		{
			MethodName: "CloseCasinoRound",
			Handler:    _BettingService_CloseCasinoRound_Handler,
		},
		{
			MethodName: "SettleVirtualBet",
			Handler:    _BettingService_SettleVirtualBet_Handler,
		},
		{
			MethodName: "CancelCasinoBet",
			Handler:    _BettingService_CancelCasinoBet_Handler,
		},
		{
			MethodName: "BetHistory",
			Handler:    _BettingService_BetHistory_Handler,
		},
		{
			MethodName: "SimulatedBetHistory",
			Handler:    _BettingService_SimulatedBetHistory_Handler,
		},
		{
			MethodName: "FindBet",
			Handler:    _BettingService_FindBet_Handler,
		},
		{
			MethodName: "UpdateBet",
			Handler:    _BettingService_UpdateBet_Handler,
		},
		{
			MethodName: "GetProbabilityFromBetID",
			Handler:    _BettingService_GetProbabilityFromBetID_Handler,
		},
		{
			MethodName: "GetCoupon",
			Handler:    _BettingService_GetCoupon_Handler,
		},
		{
			MethodName: "GamingActivity",
			Handler:    _BettingService_GamingActivity_Handler,
		},
		{
			MethodName: "GetVirtualBet",
			Handler:    _BettingService_GetVirtualBet_Handler,
		},
		{
			MethodName: "GetVirtualBets",
			Handler:    _BettingService_GetVirtualBets_Handler,
		},
		{
			MethodName: "CashoutRequest",
			Handler:    _BettingService_CashoutRequest_Handler,
		},
		{
			MethodName: "GetRetailBets",
			Handler:    _BettingService_GetRetailBets_Handler,
		},
		{
			MethodName: "GetRetailVBets",
			Handler:    _BettingService_GetRetailVBets_Handler,
		},
		{
			MethodName: "GetSalesReport",
			Handler:    _BettingService_GetSalesReport_Handler,
		},
		{
			MethodName: "GetShopUserCommissions",
			Handler:    _BettingService_GetShopUserCommissions_Handler,
		},
		{
			MethodName: "GetTotalSalesReport",
			Handler:    _BettingService_GetTotalSalesReport_Handler,
		},
		{
			MethodName: "DeletePlayerData",
			Handler:    _BettingService_DeletePlayerData_Handler,
		},
		{
			MethodName: "GetCommissions",
			Handler:    _BettingService_GetCommissions_Handler,
		},
		{
			MethodName: "GetAgentTotals",
			Handler:    _BettingService_GetAgentTotals_Handler,
		},
		{
			MethodName: "TicketsReport",
			Handler:    _BettingService_TicketsReport_Handler,
		},
		{
			MethodName: "TaxReport",
			Handler:    _BettingService_TaxReport_Handler,
		},
		{
			MethodName: "GetCodeHubTickets",
			Handler:    _BettingService_GetCodeHubTickets_Handler,
		},
		{
			MethodName: "PayoutTicket",
			Handler:    _BettingService_PayoutTicket_Handler,
		},
		{
			MethodName: "SaveSettings",
			Handler:    _BettingService_SaveSettings_Handler,
		},
		{
			MethodName: "SaveRiskSettings",
			Handler:    _BettingService_SaveRiskSettings_Handler,
		},
		{
			MethodName: "SaveUserRiskSettings",
			Handler:    _BettingService_SaveUserRiskSettings_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _BettingService_GetSettings_Handler,
		},
		{
			MethodName: "GetGlobalVariables",
			Handler:    _BettingService_GetGlobalVariables_Handler,
		},
		{
			MethodName: "GetUserRiskSettings",
			Handler:    _BettingService_GetUserRiskSettings_Handler,
		},
		{
			MethodName: "ValidateSelections",
			Handler:    _BettingService_ValidateSelections_Handler,
		},
		{
			MethodName: "ManualSettlement",
			Handler:    _BettingService_ManualSettlement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "betting.proto",
}
