version: '3.8'

services:
  go-wallet-service:
    image: ghcr.io/zoroplay/go-wallet-service:latest
    ports:
      - "9019:5000"
    env_file:
      - .env
    volumes:
      - migration-data:/app/migrations
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    networks:
      - sbenet
    restart: unless-stopped

volumes:
  migration-data:

networks:
  sbenet:
    external: true