// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.0
// source: outrights.proto

package outrights

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OutrightsService_GetFixtures_FullMethodName    = "/outrights.OutrightsService/GetFixtures"
	OutrightsService_GetOdds_FullMethodName        = "/outrights.OutrightsService/GetOdds"
	OutrightsService_GetProbability_FullMethodName = "/outrights.OutrightsService/GetProbability"
)

// OutrightsServiceClient is the client API for OutrightsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OutrightsServiceClient interface {
	GetFixtures(ctx context.Context, in *GetHighlightsRequest, opts ...grpc.CallOption) (*GetHighlightsResponse, error)
	GetOdds(ctx context.Context, in *GetOddsRequest, opts ...grpc.CallOption) (*GetOddsReply, error)
	GetProbability(ctx context.Context, in *GetOddsRequest, opts ...grpc.CallOption) (*Probability, error)
}

type outrightsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOutrightsServiceClient(cc grpc.ClientConnInterface) OutrightsServiceClient {
	return &outrightsServiceClient{cc}
}

func (c *outrightsServiceClient) GetFixtures(ctx context.Context, in *GetHighlightsRequest, opts ...grpc.CallOption) (*GetHighlightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHighlightsResponse)
	err := c.cc.Invoke(ctx, OutrightsService_GetFixtures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outrightsServiceClient) GetOdds(ctx context.Context, in *GetOddsRequest, opts ...grpc.CallOption) (*GetOddsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOddsReply)
	err := c.cc.Invoke(ctx, OutrightsService_GetOdds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outrightsServiceClient) GetProbability(ctx context.Context, in *GetOddsRequest, opts ...grpc.CallOption) (*Probability, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Probability)
	err := c.cc.Invoke(ctx, OutrightsService_GetProbability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutrightsServiceServer is the server API for OutrightsService service.
// All implementations must embed UnimplementedOutrightsServiceServer
// for forward compatibility.
type OutrightsServiceServer interface {
	GetFixtures(context.Context, *GetHighlightsRequest) (*GetHighlightsResponse, error)
	GetOdds(context.Context, *GetOddsRequest) (*GetOddsReply, error)
	GetProbability(context.Context, *GetOddsRequest) (*Probability, error)
	mustEmbedUnimplementedOutrightsServiceServer()
}

// UnimplementedOutrightsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutrightsServiceServer struct{}

func (UnimplementedOutrightsServiceServer) GetFixtures(context.Context, *GetHighlightsRequest) (*GetHighlightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFixtures not implemented")
}
func (UnimplementedOutrightsServiceServer) GetOdds(context.Context, *GetOddsRequest) (*GetOddsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOdds not implemented")
}
func (UnimplementedOutrightsServiceServer) GetProbability(context.Context, *GetOddsRequest) (*Probability, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProbability not implemented")
}
func (UnimplementedOutrightsServiceServer) mustEmbedUnimplementedOutrightsServiceServer() {}
func (UnimplementedOutrightsServiceServer) testEmbeddedByValue()                          {}

// UnsafeOutrightsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutrightsServiceServer will
// result in compilation errors.
type UnsafeOutrightsServiceServer interface {
	mustEmbedUnimplementedOutrightsServiceServer()
}

func RegisterOutrightsServiceServer(s grpc.ServiceRegistrar, srv OutrightsServiceServer) {
	// If the following call panics, it indicates UnimplementedOutrightsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutrightsService_ServiceDesc, srv)
}

func _OutrightsService_GetFixtures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHighlightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutrightsServiceServer).GetFixtures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutrightsService_GetFixtures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutrightsServiceServer).GetFixtures(ctx, req.(*GetHighlightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutrightsService_GetOdds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOddsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutrightsServiceServer).GetOdds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutrightsService_GetOdds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutrightsServiceServer).GetOdds(ctx, req.(*GetOddsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutrightsService_GetProbability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOddsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutrightsServiceServer).GetProbability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutrightsService_GetProbability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutrightsServiceServer).GetProbability(ctx, req.(*GetOddsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OutrightsService_ServiceDesc is the grpc.ServiceDesc for OutrightsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutrightsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outrights.OutrightsService",
	HandlerType: (*OutrightsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFixtures",
			Handler:    _OutrightsService_GetFixtures_Handler,
		},
		{
			MethodName: "GetOdds",
			Handler:    _OutrightsService_GetOdds_Handler,
		},
		{
			MethodName: "GetProbability",
			Handler:    _OutrightsService_GetProbability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "outrights.proto",
}
