// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.0
// source: gaming.proto

package gaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GamingService_CreateGame_FullMethodName                 = "/gaming.GamingService/CreateGame"
	GamingService_FindAllGames_FullMethodName               = "/gaming.GamingService/FindAllGames"
	GamingService_FetchGames_FullMethodName                 = "/gaming.GamingService/FetchGames"
	GamingService_FetchGamesByName_FullMethodName           = "/gaming.GamingService/FetchGamesByName"
	GamingService_AdminFetchGamesByName_FullMethodName      = "/gaming.GamingService/AdminFetchGamesByName"
	GamingService_SyncGames_FullMethodName                  = "/gaming.GamingService/SyncGames"
	GamingService_FindOneGame_FullMethodName                = "/gaming.GamingService/FindOneGame"
	GamingService_UpdateGame_FullMethodName                 = "/gaming.GamingService/UpdateGame"
	GamingService_RemoveGame_FullMethodName                 = "/gaming.GamingService/RemoveGame"
	GamingService_SaveCategory_FullMethodName               = "/gaming.GamingService/SaveCategory"
	GamingService_FetchCategories_FullMethodName            = "/gaming.GamingService/FetchCategories"
	GamingService_AddGameToCategories_FullMethodName        = "/gaming.GamingService/addGameToCategories"
	GamingService_RemoveGameToCategories_FullMethodName     = "/gaming.GamingService/removeGameToCategories"
	GamingService_AddTournamentGame_FullMethodName          = "/gaming.GamingService/addTournamentGame"
	GamingService_RemoveTournamentGame_FullMethodName       = "/gaming.GamingService/removeTournamentGame"
	GamingService_FindOneCategory_FullMethodName            = "/gaming.GamingService/findOneCategory"
	GamingService_UpdateCategory_FullMethodName             = "/gaming.GamingService/updateCategory"
	GamingService_DeleteCategory_FullMethodName             = "/gaming.GamingService/deleteCategory"
	GamingService_RegisterBonus_FullMethodName              = "/gaming.GamingService/RegisterBonus"
	GamingService_FindOneTournament_FullMethodName          = "/gaming.GamingService/findOneTournament"
	GamingService_FindAllTournaments_FullMethodName         = "/gaming.GamingService/FindAllTournaments"
	GamingService_UpdateTournament_FullMethodName           = "/gaming.GamingService/updateTournament"
	GamingService_DeleteTournament_FullMethodName           = "/gaming.GamingService/deleteTournament"
	GamingService_CreateTournament_FullMethodName           = "/gaming.GamingService/createTournament"
	GamingService_CreateProvider_FullMethodName             = "/gaming.GamingService/CreateProvider"
	GamingService_UpdateProvider_FullMethodName             = "/gaming.GamingService/UpdateProvider"
	GamingService_FindOneProvider_FullMethodName            = "/gaming.GamingService/FindOneProvider"
	GamingService_RemoveProvider_FullMethodName             = "/gaming.GamingService/RemoveProvider"
	GamingService_FindAllProviders_FullMethodName           = "/gaming.GamingService/FindAllProviders"
	GamingService_FindAdminProviders_FullMethodName         = "/gaming.GamingService/FindAdminProviders"
	GamingService_GetGames_FullMethodName                   = "/gaming.GamingService/getGames"
	GamingService_CreatePromotion_FullMethodName            = "/gaming.GamingService/CreatePromotion"
	GamingService_FindPromotions_FullMethodName             = "/gaming.GamingService/FindPromotions"
	GamingService_FindOnePromotion_FullMethodName           = "/gaming.GamingService/FindOnePromotion"
	GamingService_UpdatePromotion_FullMethodName            = "/gaming.GamingService/UpdatePromotion"
	GamingService_RemovePromotion_FullMethodName            = "/gaming.GamingService/RemovePromotion"
	GamingService_HandleCasinoBonus_FullMethodName          = "/gaming.GamingService/HandleCasinoBonus"
	GamingService_AddGameKeys_FullMethodName                = "/gaming.GamingService/AddGameKeys"
	GamingService_FetchGameKeys_FullMethodName              = "/gaming.GamingService/fetchGameKeys"
	GamingService_DeleteGameKeys_FullMethodName             = "/gaming.GamingService/deleteGameKeys"
	GamingService_FetchBonusGames_FullMethodName            = "/gaming.GamingService/fetchBonusGames"
	GamingService_HandleCasinoJackpot_FullMethodName        = "/gaming.GamingService/HandleCasinoJackpot"
	GamingService_HandleCasinoJackpotWinners_FullMethodName = "/gaming.GamingService/HandleCasinoJackpotWinners"
	GamingService_StartGame_FullMethodName                  = "/gaming.GamingService/StartGame"
	GamingService_QtechLobby_FullMethodName                 = "/gaming.GamingService/QtechLobby"
	GamingService_QueryGames_FullMethodName                 = "/gaming.GamingService/QueryGames"
	GamingService_HandleCallback_FullMethodName             = "/gaming.GamingService/HandleCallback"
	GamingService_HandleQtechCallback_FullMethodName        = "/gaming.GamingService/HandleQtechCallback"
	GamingService_HandleSpribeCallback_FullMethodName       = "/gaming.GamingService/HandleSpribeCallback"
	GamingService_HandleSmatVirtualCallback_FullMethodName  = "/gaming.GamingService/HandleSmatVirtualCallback"
	GamingService_XpressLogin_FullMethodName                = "/gaming.GamingService/XpressLogin"
	GamingService_XpressBalance_FullMethodName              = "/gaming.GamingService/XpressBalance"
	GamingService_XpressDebit_FullMethodName                = "/gaming.GamingService/XpressDebit"
	GamingService_XpressCredit_FullMethodName               = "/gaming.GamingService/XpressCredit"
	GamingService_XpressRollback_FullMethodName             = "/gaming.GamingService/XpressRollback"
	GamingService_XpressLogout_FullMethodName               = "/gaming.GamingService/XpressLogout"
	GamingService_StartSmatGame_FullMethodName              = "/gaming.GamingService/StartSmatGame"
)

// GamingServiceClient is the client API for GamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GamingServiceClient interface {
	CreateGame(ctx context.Context, in *CreateGameDto, opts ...grpc.CallOption) (*Game, error)
	FindAllGames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Games, error)
	FetchGames(ctx context.Context, in *FetchGamesRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	FetchGamesByName(ctx context.Context, in *FetchGamesRequest, opts ...grpc.CallOption) (*Games, error)
	AdminFetchGamesByName(ctx context.Context, in *FetchGamesRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	SyncGames(ctx context.Context, in *SyncGameDto, opts ...grpc.CallOption) (*Games, error)
	FindOneGame(ctx context.Context, in *FindOneGameDto, opts ...grpc.CallOption) (*Game, error)
	UpdateGame(ctx context.Context, in *UpdateGameDto, opts ...grpc.CallOption) (*Game, error)
	RemoveGame(ctx context.Context, in *UpdateGameDto, opts ...grpc.CallOption) (*Game, error)
	SaveCategory(ctx context.Context, in *SaveCategoryRequest, opts ...grpc.CallOption) (*Category, error)
	FetchCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Categories, error)
	AddGameToCategories(ctx context.Context, in *AddGameToCategoriesDto, opts ...grpc.CallOption) (*Game, error)
	RemoveGameToCategories(ctx context.Context, in *AddGameToCategoriesDto, opts ...grpc.CallOption) (*Game, error)
	AddTournamentGame(ctx context.Context, in *AddGameToTournamentDto, opts ...grpc.CallOption) (*TournamentResponse, error)
	RemoveTournamentGame(ctx context.Context, in *AddGameToTournamentDto, opts ...grpc.CallOption) (*Empty, error)
	FindOneCategory(ctx context.Context, in *FindOneCategoryDto, opts ...grpc.CallOption) (*Category, error)
	UpdateCategory(ctx context.Context, in *SaveCategoryRequest, opts ...grpc.CallOption) (*Category, error)
	DeleteCategory(ctx context.Context, in *FindOneCategoryDto, opts ...grpc.CallOption) (*Empty, error)
	RegisterBonus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error)
	FindOneTournament(ctx context.Context, in *FindOneTournamentDto, opts ...grpc.CallOption) (*Tournament, error)
	FindAllTournaments(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Tournaments, error)
	UpdateTournament(ctx context.Context, in *CreateTournamentDto, opts ...grpc.CallOption) (*Tournament, error)
	DeleteTournament(ctx context.Context, in *FindOneTournamentDto, opts ...grpc.CallOption) (*Empty, error)
	CreateTournament(ctx context.Context, in *CreateTournamentDto, opts ...grpc.CallOption) (*Tournament, error)
	CreateProvider(ctx context.Context, in *CreateProviderDto, opts ...grpc.CallOption) (*CommonResponse, error)
	UpdateProvider(ctx context.Context, in *CreateProviderDto, opts ...grpc.CallOption) (*CommonResponse, error)
	FindOneProvider(ctx context.Context, in *FindOneGameDto, opts ...grpc.CallOption) (*CommonResponse, error)
	RemoveProvider(ctx context.Context, in *CreateProviderDto, opts ...grpc.CallOption) (*CommonResponse, error)
	FindAllProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error)
	FindAdminProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error)
	GetGames(ctx context.Context, in *GetGamesRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	CreatePromotion(ctx context.Context, in *CreatePromotionRequest, opts ...grpc.CallOption) (*Promotion, error)
	FindPromotions(ctx context.Context, in *GetPromotions, opts ...grpc.CallOption) (*Promotions, error)
	FindOnePromotion(ctx context.Context, in *FindOnePromotionDto, opts ...grpc.CallOption) (*Promotion, error)
	UpdatePromotion(ctx context.Context, in *CreatePromotionRequest, opts ...grpc.CallOption) (*Promotion, error)
	RemovePromotion(ctx context.Context, in *FindOnePromotionDto, opts ...grpc.CallOption) (*Empty, error)
	HandleCasinoBonus(ctx context.Context, in *CreateBonusRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	AddGameKeys(ctx context.Context, in *CreateGameKeyRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	FetchGameKeys(ctx context.Context, in *GetKeysRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	DeleteGameKeys(ctx context.Context, in *FindOneGameDto, opts ...grpc.CallOption) (*CommonResponse, error)
	FetchBonusGames(ctx context.Context, in *BonusGameRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	HandleCasinoJackpot(ctx context.Context, in *SyncGameDto, opts ...grpc.CallOption) (*CommonResponse, error)
	HandleCasinoJackpotWinners(ctx context.Context, in *SyncGameDto, opts ...grpc.CallOption) (*CommonResponse, error)
	StartGame(ctx context.Context, in *StartGameDto, opts ...grpc.CallOption) (*StartGameResponse, error)
	QtechLobby(ctx context.Context, in *StartGameDto, opts ...grpc.CallOption) (*StartGameResponse, error)
	QueryGames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PaginationDto, Games], error)
	HandleCallback(ctx context.Context, in *CallbackGameDto, opts ...grpc.CallOption) (*CallbackResponse, error)
	HandleQtechCallback(ctx context.Context, in *QtechCallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error)
	HandleSpribeCallback(ctx context.Context, in *SpribeCallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error)
	HandleSmatVirtualCallback(ctx context.Context, in *SmatVirtualCallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error)
	XpressLogin(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error)
	XpressBalance(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error)
	XpressDebit(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error)
	XpressCredit(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error)
	XpressRollback(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error)
	XpressLogout(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error)
	StartSmatGame(ctx context.Context, in *StartDto, opts ...grpc.CallOption) (*StartGameResponse, error)
}

type gamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGamingServiceClient(cc grpc.ClientConnInterface) GamingServiceClient {
	return &gamingServiceClient{cc}
}

func (c *gamingServiceClient) CreateGame(ctx context.Context, in *CreateGameDto, opts ...grpc.CallOption) (*Game, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Game)
	err := c.cc.Invoke(ctx, GamingService_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FindAllGames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Games, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Games)
	err := c.cc.Invoke(ctx, GamingService_FindAllGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FetchGames(ctx context.Context, in *FetchGamesRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, GamingService_FetchGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FetchGamesByName(ctx context.Context, in *FetchGamesRequest, opts ...grpc.CallOption) (*Games, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Games)
	err := c.cc.Invoke(ctx, GamingService_FetchGamesByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) AdminFetchGamesByName(ctx context.Context, in *FetchGamesRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_AdminFetchGamesByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) SyncGames(ctx context.Context, in *SyncGameDto, opts ...grpc.CallOption) (*Games, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Games)
	err := c.cc.Invoke(ctx, GamingService_SyncGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FindOneGame(ctx context.Context, in *FindOneGameDto, opts ...grpc.CallOption) (*Game, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Game)
	err := c.cc.Invoke(ctx, GamingService_FindOneGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) UpdateGame(ctx context.Context, in *UpdateGameDto, opts ...grpc.CallOption) (*Game, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Game)
	err := c.cc.Invoke(ctx, GamingService_UpdateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) RemoveGame(ctx context.Context, in *UpdateGameDto, opts ...grpc.CallOption) (*Game, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Game)
	err := c.cc.Invoke(ctx, GamingService_RemoveGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) SaveCategory(ctx context.Context, in *SaveCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Category)
	err := c.cc.Invoke(ctx, GamingService_SaveCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FetchCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Categories, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Categories)
	err := c.cc.Invoke(ctx, GamingService_FetchCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) AddGameToCategories(ctx context.Context, in *AddGameToCategoriesDto, opts ...grpc.CallOption) (*Game, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Game)
	err := c.cc.Invoke(ctx, GamingService_AddGameToCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) RemoveGameToCategories(ctx context.Context, in *AddGameToCategoriesDto, opts ...grpc.CallOption) (*Game, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Game)
	err := c.cc.Invoke(ctx, GamingService_RemoveGameToCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) AddTournamentGame(ctx context.Context, in *AddGameToTournamentDto, opts ...grpc.CallOption) (*TournamentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TournamentResponse)
	err := c.cc.Invoke(ctx, GamingService_AddTournamentGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) RemoveTournamentGame(ctx context.Context, in *AddGameToTournamentDto, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GamingService_RemoveTournamentGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FindOneCategory(ctx context.Context, in *FindOneCategoryDto, opts ...grpc.CallOption) (*Category, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Category)
	err := c.cc.Invoke(ctx, GamingService_FindOneCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) UpdateCategory(ctx context.Context, in *SaveCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Category)
	err := c.cc.Invoke(ctx, GamingService_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) DeleteCategory(ctx context.Context, in *FindOneCategoryDto, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GamingService_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) RegisterBonus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_RegisterBonus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FindOneTournament(ctx context.Context, in *FindOneTournamentDto, opts ...grpc.CallOption) (*Tournament, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tournament)
	err := c.cc.Invoke(ctx, GamingService_FindOneTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FindAllTournaments(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Tournaments, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tournaments)
	err := c.cc.Invoke(ctx, GamingService_FindAllTournaments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) UpdateTournament(ctx context.Context, in *CreateTournamentDto, opts ...grpc.CallOption) (*Tournament, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tournament)
	err := c.cc.Invoke(ctx, GamingService_UpdateTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) DeleteTournament(ctx context.Context, in *FindOneTournamentDto, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GamingService_DeleteTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) CreateTournament(ctx context.Context, in *CreateTournamentDto, opts ...grpc.CallOption) (*Tournament, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tournament)
	err := c.cc.Invoke(ctx, GamingService_CreateTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) CreateProvider(ctx context.Context, in *CreateProviderDto, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_CreateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) UpdateProvider(ctx context.Context, in *CreateProviderDto, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_UpdateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FindOneProvider(ctx context.Context, in *FindOneGameDto, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_FindOneProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) RemoveProvider(ctx context.Context, in *CreateProviderDto, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_RemoveProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FindAllProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_FindAllProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FindAdminProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_FindAdminProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) GetGames(ctx context.Context, in *GetGamesRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, GamingService_GetGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) CreatePromotion(ctx context.Context, in *CreatePromotionRequest, opts ...grpc.CallOption) (*Promotion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Promotion)
	err := c.cc.Invoke(ctx, GamingService_CreatePromotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FindPromotions(ctx context.Context, in *GetPromotions, opts ...grpc.CallOption) (*Promotions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Promotions)
	err := c.cc.Invoke(ctx, GamingService_FindPromotions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FindOnePromotion(ctx context.Context, in *FindOnePromotionDto, opts ...grpc.CallOption) (*Promotion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Promotion)
	err := c.cc.Invoke(ctx, GamingService_FindOnePromotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) UpdatePromotion(ctx context.Context, in *CreatePromotionRequest, opts ...grpc.CallOption) (*Promotion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Promotion)
	err := c.cc.Invoke(ctx, GamingService_UpdatePromotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) RemovePromotion(ctx context.Context, in *FindOnePromotionDto, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GamingService_RemovePromotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) HandleCasinoBonus(ctx context.Context, in *CreateBonusRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_HandleCasinoBonus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) AddGameKeys(ctx context.Context, in *CreateGameKeyRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_AddGameKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FetchGameKeys(ctx context.Context, in *GetKeysRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_FetchGameKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) DeleteGameKeys(ctx context.Context, in *FindOneGameDto, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_DeleteGameKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) FetchBonusGames(ctx context.Context, in *BonusGameRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_FetchBonusGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) HandleCasinoJackpot(ctx context.Context, in *SyncGameDto, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_HandleCasinoJackpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) HandleCasinoJackpotWinners(ctx context.Context, in *SyncGameDto, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, GamingService_HandleCasinoJackpotWinners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) StartGame(ctx context.Context, in *StartGameDto, opts ...grpc.CallOption) (*StartGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, GamingService_StartGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) QtechLobby(ctx context.Context, in *StartGameDto, opts ...grpc.CallOption) (*StartGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, GamingService_QtechLobby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) QueryGames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PaginationDto, Games], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GamingService_ServiceDesc.Streams[0], GamingService_QueryGames_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PaginationDto, Games]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GamingService_QueryGamesClient = grpc.BidiStreamingClient[PaginationDto, Games]

func (c *gamingServiceClient) HandleCallback(ctx context.Context, in *CallbackGameDto, opts ...grpc.CallOption) (*CallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallbackResponse)
	err := c.cc.Invoke(ctx, GamingService_HandleCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) HandleQtechCallback(ctx context.Context, in *QtechCallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallbackResponse)
	err := c.cc.Invoke(ctx, GamingService_HandleQtechCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) HandleSpribeCallback(ctx context.Context, in *SpribeCallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallbackResponse)
	err := c.cc.Invoke(ctx, GamingService_HandleSpribeCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) HandleSmatVirtualCallback(ctx context.Context, in *SmatVirtualCallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallbackResponse)
	err := c.cc.Invoke(ctx, GamingService_HandleSmatVirtualCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) XpressLogin(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XpressResponse)
	err := c.cc.Invoke(ctx, GamingService_XpressLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) XpressBalance(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XpressResponse)
	err := c.cc.Invoke(ctx, GamingService_XpressBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) XpressDebit(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XpressResponse)
	err := c.cc.Invoke(ctx, GamingService_XpressDebit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) XpressCredit(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XpressResponse)
	err := c.cc.Invoke(ctx, GamingService_XpressCredit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) XpressRollback(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XpressResponse)
	err := c.cc.Invoke(ctx, GamingService_XpressRollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) XpressLogout(ctx context.Context, in *XpressRequest, opts ...grpc.CallOption) (*XpressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XpressResponse)
	err := c.cc.Invoke(ctx, GamingService_XpressLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamingServiceClient) StartSmatGame(ctx context.Context, in *StartDto, opts ...grpc.CallOption) (*StartGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, GamingService_StartSmatGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GamingServiceServer is the server API for GamingService service.
// All implementations must embed UnimplementedGamingServiceServer
// for forward compatibility.
type GamingServiceServer interface {
	CreateGame(context.Context, *CreateGameDto) (*Game, error)
	FindAllGames(context.Context, *Empty) (*Games, error)
	FetchGames(context.Context, *FetchGamesRequest) (*CommonResponseArray, error)
	FetchGamesByName(context.Context, *FetchGamesRequest) (*Games, error)
	AdminFetchGamesByName(context.Context, *FetchGamesRequest) (*CommonResponse, error)
	SyncGames(context.Context, *SyncGameDto) (*Games, error)
	FindOneGame(context.Context, *FindOneGameDto) (*Game, error)
	UpdateGame(context.Context, *UpdateGameDto) (*Game, error)
	RemoveGame(context.Context, *UpdateGameDto) (*Game, error)
	SaveCategory(context.Context, *SaveCategoryRequest) (*Category, error)
	FetchCategories(context.Context, *Empty) (*Categories, error)
	AddGameToCategories(context.Context, *AddGameToCategoriesDto) (*Game, error)
	RemoveGameToCategories(context.Context, *AddGameToCategoriesDto) (*Game, error)
	AddTournamentGame(context.Context, *AddGameToTournamentDto) (*TournamentResponse, error)
	RemoveTournamentGame(context.Context, *AddGameToTournamentDto) (*Empty, error)
	FindOneCategory(context.Context, *FindOneCategoryDto) (*Category, error)
	UpdateCategory(context.Context, *SaveCategoryRequest) (*Category, error)
	DeleteCategory(context.Context, *FindOneCategoryDto) (*Empty, error)
	RegisterBonus(context.Context, *Empty) (*CommonResponse, error)
	FindOneTournament(context.Context, *FindOneTournamentDto) (*Tournament, error)
	FindAllTournaments(context.Context, *Empty) (*Tournaments, error)
	UpdateTournament(context.Context, *CreateTournamentDto) (*Tournament, error)
	DeleteTournament(context.Context, *FindOneTournamentDto) (*Empty, error)
	CreateTournament(context.Context, *CreateTournamentDto) (*Tournament, error)
	CreateProvider(context.Context, *CreateProviderDto) (*CommonResponse, error)
	UpdateProvider(context.Context, *CreateProviderDto) (*CommonResponse, error)
	FindOneProvider(context.Context, *FindOneGameDto) (*CommonResponse, error)
	RemoveProvider(context.Context, *CreateProviderDto) (*CommonResponse, error)
	FindAllProviders(context.Context, *Empty) (*CommonResponse, error)
	FindAdminProviders(context.Context, *Empty) (*CommonResponse, error)
	GetGames(context.Context, *GetGamesRequest) (*CommonResponseArray, error)
	CreatePromotion(context.Context, *CreatePromotionRequest) (*Promotion, error)
	FindPromotions(context.Context, *GetPromotions) (*Promotions, error)
	FindOnePromotion(context.Context, *FindOnePromotionDto) (*Promotion, error)
	UpdatePromotion(context.Context, *CreatePromotionRequest) (*Promotion, error)
	RemovePromotion(context.Context, *FindOnePromotionDto) (*Empty, error)
	HandleCasinoBonus(context.Context, *CreateBonusRequest) (*CommonResponse, error)
	AddGameKeys(context.Context, *CreateGameKeyRequest) (*CommonResponse, error)
	FetchGameKeys(context.Context, *GetKeysRequest) (*CommonResponse, error)
	DeleteGameKeys(context.Context, *FindOneGameDto) (*CommonResponse, error)
	FetchBonusGames(context.Context, *BonusGameRequest) (*CommonResponse, error)
	HandleCasinoJackpot(context.Context, *SyncGameDto) (*CommonResponse, error)
	HandleCasinoJackpotWinners(context.Context, *SyncGameDto) (*CommonResponse, error)
	StartGame(context.Context, *StartGameDto) (*StartGameResponse, error)
	QtechLobby(context.Context, *StartGameDto) (*StartGameResponse, error)
	QueryGames(grpc.BidiStreamingServer[PaginationDto, Games]) error
	HandleCallback(context.Context, *CallbackGameDto) (*CallbackResponse, error)
	HandleQtechCallback(context.Context, *QtechCallbackRequest) (*CallbackResponse, error)
	HandleSpribeCallback(context.Context, *SpribeCallbackRequest) (*CallbackResponse, error)
	HandleSmatVirtualCallback(context.Context, *SmatVirtualCallbackRequest) (*CallbackResponse, error)
	XpressLogin(context.Context, *XpressRequest) (*XpressResponse, error)
	XpressBalance(context.Context, *XpressRequest) (*XpressResponse, error)
	XpressDebit(context.Context, *XpressRequest) (*XpressResponse, error)
	XpressCredit(context.Context, *XpressRequest) (*XpressResponse, error)
	XpressRollback(context.Context, *XpressRequest) (*XpressResponse, error)
	XpressLogout(context.Context, *XpressRequest) (*XpressResponse, error)
	StartSmatGame(context.Context, *StartDto) (*StartGameResponse, error)
	mustEmbedUnimplementedGamingServiceServer()
}

// UnimplementedGamingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGamingServiceServer struct{}

func (UnimplementedGamingServiceServer) CreateGame(context.Context, *CreateGameDto) (*Game, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedGamingServiceServer) FindAllGames(context.Context, *Empty) (*Games, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAllGames not implemented")
}
func (UnimplementedGamingServiceServer) FetchGames(context.Context, *FetchGamesRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchGames not implemented")
}
func (UnimplementedGamingServiceServer) FetchGamesByName(context.Context, *FetchGamesRequest) (*Games, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchGamesByName not implemented")
}
func (UnimplementedGamingServiceServer) AdminFetchGamesByName(context.Context, *FetchGamesRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminFetchGamesByName not implemented")
}
func (UnimplementedGamingServiceServer) SyncGames(context.Context, *SyncGameDto) (*Games, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncGames not implemented")
}
func (UnimplementedGamingServiceServer) FindOneGame(context.Context, *FindOneGameDto) (*Game, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOneGame not implemented")
}
func (UnimplementedGamingServiceServer) UpdateGame(context.Context, *UpdateGameDto) (*Game, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGame not implemented")
}
func (UnimplementedGamingServiceServer) RemoveGame(context.Context, *UpdateGameDto) (*Game, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveGame not implemented")
}
func (UnimplementedGamingServiceServer) SaveCategory(context.Context, *SaveCategoryRequest) (*Category, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCategory not implemented")
}
func (UnimplementedGamingServiceServer) FetchCategories(context.Context, *Empty) (*Categories, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchCategories not implemented")
}
func (UnimplementedGamingServiceServer) AddGameToCategories(context.Context, *AddGameToCategoriesDto) (*Game, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGameToCategories not implemented")
}
func (UnimplementedGamingServiceServer) RemoveGameToCategories(context.Context, *AddGameToCategoriesDto) (*Game, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveGameToCategories not implemented")
}
func (UnimplementedGamingServiceServer) AddTournamentGame(context.Context, *AddGameToTournamentDto) (*TournamentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTournamentGame not implemented")
}
func (UnimplementedGamingServiceServer) RemoveTournamentGame(context.Context, *AddGameToTournamentDto) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTournamentGame not implemented")
}
func (UnimplementedGamingServiceServer) FindOneCategory(context.Context, *FindOneCategoryDto) (*Category, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOneCategory not implemented")
}
func (UnimplementedGamingServiceServer) UpdateCategory(context.Context, *SaveCategoryRequest) (*Category, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedGamingServiceServer) DeleteCategory(context.Context, *FindOneCategoryDto) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedGamingServiceServer) RegisterBonus(context.Context, *Empty) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBonus not implemented")
}
func (UnimplementedGamingServiceServer) FindOneTournament(context.Context, *FindOneTournamentDto) (*Tournament, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOneTournament not implemented")
}
func (UnimplementedGamingServiceServer) FindAllTournaments(context.Context, *Empty) (*Tournaments, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAllTournaments not implemented")
}
func (UnimplementedGamingServiceServer) UpdateTournament(context.Context, *CreateTournamentDto) (*Tournament, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTournament not implemented")
}
func (UnimplementedGamingServiceServer) DeleteTournament(context.Context, *FindOneTournamentDto) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTournament not implemented")
}
func (UnimplementedGamingServiceServer) CreateTournament(context.Context, *CreateTournamentDto) (*Tournament, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTournament not implemented")
}
func (UnimplementedGamingServiceServer) CreateProvider(context.Context, *CreateProviderDto) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProvider not implemented")
}
func (UnimplementedGamingServiceServer) UpdateProvider(context.Context, *CreateProviderDto) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProvider not implemented")
}
func (UnimplementedGamingServiceServer) FindOneProvider(context.Context, *FindOneGameDto) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOneProvider not implemented")
}
func (UnimplementedGamingServiceServer) RemoveProvider(context.Context, *CreateProviderDto) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveProvider not implemented")
}
func (UnimplementedGamingServiceServer) FindAllProviders(context.Context, *Empty) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAllProviders not implemented")
}
func (UnimplementedGamingServiceServer) FindAdminProviders(context.Context, *Empty) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAdminProviders not implemented")
}
func (UnimplementedGamingServiceServer) GetGames(context.Context, *GetGamesRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGames not implemented")
}
func (UnimplementedGamingServiceServer) CreatePromotion(context.Context, *CreatePromotionRequest) (*Promotion, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePromotion not implemented")
}
func (UnimplementedGamingServiceServer) FindPromotions(context.Context, *GetPromotions) (*Promotions, error) {
	return nil, status.Error(codes.Unimplemented, "method FindPromotions not implemented")
}
func (UnimplementedGamingServiceServer) FindOnePromotion(context.Context, *FindOnePromotionDto) (*Promotion, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOnePromotion not implemented")
}
func (UnimplementedGamingServiceServer) UpdatePromotion(context.Context, *CreatePromotionRequest) (*Promotion, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePromotion not implemented")
}
func (UnimplementedGamingServiceServer) RemovePromotion(context.Context, *FindOnePromotionDto) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePromotion not implemented")
}
func (UnimplementedGamingServiceServer) HandleCasinoBonus(context.Context, *CreateBonusRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCasinoBonus not implemented")
}
func (UnimplementedGamingServiceServer) AddGameKeys(context.Context, *CreateGameKeyRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGameKeys not implemented")
}
func (UnimplementedGamingServiceServer) FetchGameKeys(context.Context, *GetKeysRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchGameKeys not implemented")
}
func (UnimplementedGamingServiceServer) DeleteGameKeys(context.Context, *FindOneGameDto) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGameKeys not implemented")
}
func (UnimplementedGamingServiceServer) FetchBonusGames(context.Context, *BonusGameRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchBonusGames not implemented")
}
func (UnimplementedGamingServiceServer) HandleCasinoJackpot(context.Context, *SyncGameDto) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCasinoJackpot not implemented")
}
func (UnimplementedGamingServiceServer) HandleCasinoJackpotWinners(context.Context, *SyncGameDto) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCasinoJackpotWinners not implemented")
}
func (UnimplementedGamingServiceServer) StartGame(context.Context, *StartGameDto) (*StartGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedGamingServiceServer) QtechLobby(context.Context, *StartGameDto) (*StartGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QtechLobby not implemented")
}
func (UnimplementedGamingServiceServer) QueryGames(grpc.BidiStreamingServer[PaginationDto, Games]) error {
	return status.Error(codes.Unimplemented, "method QueryGames not implemented")
}
func (UnimplementedGamingServiceServer) HandleCallback(context.Context, *CallbackGameDto) (*CallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCallback not implemented")
}
func (UnimplementedGamingServiceServer) HandleQtechCallback(context.Context, *QtechCallbackRequest) (*CallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleQtechCallback not implemented")
}
func (UnimplementedGamingServiceServer) HandleSpribeCallback(context.Context, *SpribeCallbackRequest) (*CallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleSpribeCallback not implemented")
}
func (UnimplementedGamingServiceServer) HandleSmatVirtualCallback(context.Context, *SmatVirtualCallbackRequest) (*CallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleSmatVirtualCallback not implemented")
}
func (UnimplementedGamingServiceServer) XpressLogin(context.Context, *XpressRequest) (*XpressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method XpressLogin not implemented")
}
func (UnimplementedGamingServiceServer) XpressBalance(context.Context, *XpressRequest) (*XpressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method XpressBalance not implemented")
}
func (UnimplementedGamingServiceServer) XpressDebit(context.Context, *XpressRequest) (*XpressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method XpressDebit not implemented")
}
func (UnimplementedGamingServiceServer) XpressCredit(context.Context, *XpressRequest) (*XpressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method XpressCredit not implemented")
}
func (UnimplementedGamingServiceServer) XpressRollback(context.Context, *XpressRequest) (*XpressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method XpressRollback not implemented")
}
func (UnimplementedGamingServiceServer) XpressLogout(context.Context, *XpressRequest) (*XpressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method XpressLogout not implemented")
}
func (UnimplementedGamingServiceServer) StartSmatGame(context.Context, *StartDto) (*StartGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSmatGame not implemented")
}
func (UnimplementedGamingServiceServer) mustEmbedUnimplementedGamingServiceServer() {}
func (UnimplementedGamingServiceServer) testEmbeddedByValue()                       {}

// UnsafeGamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GamingServiceServer will
// result in compilation errors.
type UnsafeGamingServiceServer interface {
	mustEmbedUnimplementedGamingServiceServer()
}

func RegisterGamingServiceServer(s grpc.ServiceRegistrar, srv GamingServiceServer) {
	// If the following call panics, it indicates UnimplementedGamingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GamingService_ServiceDesc, srv)
}

func _GamingService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).CreateGame(ctx, req.(*CreateGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FindAllGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FindAllGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FindAllGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FindAllGames(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FetchGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FetchGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FetchGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FetchGames(ctx, req.(*FetchGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FetchGamesByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FetchGamesByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FetchGamesByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FetchGamesByName(ctx, req.(*FetchGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_AdminFetchGamesByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).AdminFetchGamesByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_AdminFetchGamesByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).AdminFetchGamesByName(ctx, req.(*FetchGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_SyncGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).SyncGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_SyncGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).SyncGames(ctx, req.(*SyncGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FindOneGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FindOneGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FindOneGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FindOneGame(ctx, req.(*FindOneGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_UpdateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).UpdateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_UpdateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).UpdateGame(ctx, req.(*UpdateGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_RemoveGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).RemoveGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_RemoveGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).RemoveGame(ctx, req.(*UpdateGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_SaveCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).SaveCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_SaveCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).SaveCategory(ctx, req.(*SaveCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FetchCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FetchCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FetchCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FetchCategories(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_AddGameToCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGameToCategoriesDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).AddGameToCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_AddGameToCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).AddGameToCategories(ctx, req.(*AddGameToCategoriesDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_RemoveGameToCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGameToCategoriesDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).RemoveGameToCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_RemoveGameToCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).RemoveGameToCategories(ctx, req.(*AddGameToCategoriesDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_AddTournamentGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGameToTournamentDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).AddTournamentGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_AddTournamentGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).AddTournamentGame(ctx, req.(*AddGameToTournamentDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_RemoveTournamentGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGameToTournamentDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).RemoveTournamentGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_RemoveTournamentGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).RemoveTournamentGame(ctx, req.(*AddGameToTournamentDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FindOneCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneCategoryDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FindOneCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FindOneCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FindOneCategory(ctx, req.(*FindOneCategoryDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).UpdateCategory(ctx, req.(*SaveCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneCategoryDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).DeleteCategory(ctx, req.(*FindOneCategoryDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_RegisterBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).RegisterBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_RegisterBonus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).RegisterBonus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FindOneTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneTournamentDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FindOneTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FindOneTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FindOneTournament(ctx, req.(*FindOneTournamentDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FindAllTournaments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FindAllTournaments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FindAllTournaments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FindAllTournaments(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_UpdateTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTournamentDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).UpdateTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_UpdateTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).UpdateTournament(ctx, req.(*CreateTournamentDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_DeleteTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneTournamentDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).DeleteTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_DeleteTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).DeleteTournament(ctx, req.(*FindOneTournamentDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_CreateTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTournamentDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).CreateTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_CreateTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).CreateTournament(ctx, req.(*CreateTournamentDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_CreateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProviderDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).CreateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_CreateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).CreateProvider(ctx, req.(*CreateProviderDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_UpdateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProviderDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).UpdateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_UpdateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).UpdateProvider(ctx, req.(*CreateProviderDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FindOneProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FindOneProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FindOneProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FindOneProvider(ctx, req.(*FindOneGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_RemoveProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProviderDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).RemoveProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_RemoveProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).RemoveProvider(ctx, req.(*CreateProviderDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FindAllProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FindAllProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FindAllProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FindAllProviders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FindAdminProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FindAdminProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FindAdminProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FindAdminProviders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_GetGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).GetGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_GetGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).GetGames(ctx, req.(*GetGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_CreatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).CreatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_CreatePromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).CreatePromotion(ctx, req.(*CreatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FindPromotions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromotions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FindPromotions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FindPromotions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FindPromotions(ctx, req.(*GetPromotions))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FindOnePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOnePromotionDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FindOnePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FindOnePromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FindOnePromotion(ctx, req.(*FindOnePromotionDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_UpdatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).UpdatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_UpdatePromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).UpdatePromotion(ctx, req.(*CreatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_RemovePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOnePromotionDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).RemovePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_RemovePromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).RemovePromotion(ctx, req.(*FindOnePromotionDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_HandleCasinoBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).HandleCasinoBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_HandleCasinoBonus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).HandleCasinoBonus(ctx, req.(*CreateBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_AddGameKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).AddGameKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_AddGameKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).AddGameKeys(ctx, req.(*CreateGameKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FetchGameKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FetchGameKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FetchGameKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FetchGameKeys(ctx, req.(*GetKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_DeleteGameKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).DeleteGameKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_DeleteGameKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).DeleteGameKeys(ctx, req.(*FindOneGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_FetchBonusGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BonusGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).FetchBonusGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_FetchBonusGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).FetchBonusGames(ctx, req.(*BonusGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_HandleCasinoJackpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).HandleCasinoJackpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_HandleCasinoJackpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).HandleCasinoJackpot(ctx, req.(*SyncGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_HandleCasinoJackpotWinners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).HandleCasinoJackpotWinners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_HandleCasinoJackpotWinners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).HandleCasinoJackpotWinners(ctx, req.(*SyncGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_StartGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).StartGame(ctx, req.(*StartGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_QtechLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).QtechLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_QtechLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).QtechLobby(ctx, req.(*StartGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_QueryGames_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GamingServiceServer).QueryGames(&grpc.GenericServerStream[PaginationDto, Games]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GamingService_QueryGamesServer = grpc.BidiStreamingServer[PaginationDto, Games]

func _GamingService_HandleCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackGameDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).HandleCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_HandleCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).HandleCallback(ctx, req.(*CallbackGameDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_HandleQtechCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QtechCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).HandleQtechCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_HandleQtechCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).HandleQtechCallback(ctx, req.(*QtechCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_HandleSpribeCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpribeCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).HandleSpribeCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_HandleSpribeCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).HandleSpribeCallback(ctx, req.(*SpribeCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_HandleSmatVirtualCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmatVirtualCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).HandleSmatVirtualCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_HandleSmatVirtualCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).HandleSmatVirtualCallback(ctx, req.(*SmatVirtualCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_XpressLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XpressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).XpressLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_XpressLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).XpressLogin(ctx, req.(*XpressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_XpressBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XpressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).XpressBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_XpressBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).XpressBalance(ctx, req.(*XpressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_XpressDebit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XpressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).XpressDebit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_XpressDebit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).XpressDebit(ctx, req.(*XpressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_XpressCredit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XpressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).XpressCredit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_XpressCredit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).XpressCredit(ctx, req.(*XpressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_XpressRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XpressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).XpressRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_XpressRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).XpressRollback(ctx, req.(*XpressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_XpressLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XpressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).XpressLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_XpressLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).XpressLogout(ctx, req.(*XpressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamingService_StartSmatGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamingServiceServer).StartSmatGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamingService_StartSmatGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamingServiceServer).StartSmatGame(ctx, req.(*StartDto))
	}
	return interceptor(ctx, in, info, handler)
}

// GamingService_ServiceDesc is the grpc.ServiceDesc for GamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gaming.GamingService",
	HandlerType: (*GamingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _GamingService_CreateGame_Handler,
		},
		{
			MethodName: "FindAllGames",
			Handler:    _GamingService_FindAllGames_Handler,
		},
		{
			MethodName: "FetchGames",
			Handler:    _GamingService_FetchGames_Handler,
		},
		{
			MethodName: "FetchGamesByName",
			Handler:    _GamingService_FetchGamesByName_Handler,
		},
		{
			MethodName: "AdminFetchGamesByName",
			Handler:    _GamingService_AdminFetchGamesByName_Handler,
		},
		{
			MethodName: "SyncGames",
			Handler:    _GamingService_SyncGames_Handler,
		},
		{
			MethodName: "FindOneGame",
			Handler:    _GamingService_FindOneGame_Handler,
		},
		{
			MethodName: "UpdateGame",
			Handler:    _GamingService_UpdateGame_Handler,
		},
		{
			MethodName: "RemoveGame",
			Handler:    _GamingService_RemoveGame_Handler,
		},
		{
			MethodName: "SaveCategory",
			Handler:    _GamingService_SaveCategory_Handler,
		},
		{
			MethodName: "FetchCategories",
			Handler:    _GamingService_FetchCategories_Handler,
		},
		{
			MethodName: "addGameToCategories",
			Handler:    _GamingService_AddGameToCategories_Handler,
		},
		{
			MethodName: "removeGameToCategories",
			Handler:    _GamingService_RemoveGameToCategories_Handler,
		},
		{
			MethodName: "addTournamentGame",
			Handler:    _GamingService_AddTournamentGame_Handler,
		},
		{
			MethodName: "removeTournamentGame",
			Handler:    _GamingService_RemoveTournamentGame_Handler,
		},
		{
			MethodName: "findOneCategory",
			Handler:    _GamingService_FindOneCategory_Handler,
		},
		{
			MethodName: "updateCategory",
			Handler:    _GamingService_UpdateCategory_Handler,
		},
		{
			MethodName: "deleteCategory",
			Handler:    _GamingService_DeleteCategory_Handler,
		},
		{
			MethodName: "RegisterBonus",
			Handler:    _GamingService_RegisterBonus_Handler,
		},
		{
			MethodName: "findOneTournament",
			Handler:    _GamingService_FindOneTournament_Handler,
		},
		{
			MethodName: "FindAllTournaments",
			Handler:    _GamingService_FindAllTournaments_Handler,
		},
		{
			MethodName: "updateTournament",
			Handler:    _GamingService_UpdateTournament_Handler,
		},
		{
			MethodName: "deleteTournament",
			Handler:    _GamingService_DeleteTournament_Handler,
		},
		{
			MethodName: "createTournament",
			Handler:    _GamingService_CreateTournament_Handler,
		},
		{
			MethodName: "CreateProvider",
			Handler:    _GamingService_CreateProvider_Handler,
		},
		{
			MethodName: "UpdateProvider",
			Handler:    _GamingService_UpdateProvider_Handler,
		},
		{
			MethodName: "FindOneProvider",
			Handler:    _GamingService_FindOneProvider_Handler,
		},
		{
			MethodName: "RemoveProvider",
			Handler:    _GamingService_RemoveProvider_Handler,
		},
		{
			MethodName: "FindAllProviders",
			Handler:    _GamingService_FindAllProviders_Handler,
		},
		{
			MethodName: "FindAdminProviders",
			Handler:    _GamingService_FindAdminProviders_Handler,
		},
		{
			MethodName: "getGames",
			Handler:    _GamingService_GetGames_Handler,
		},
		{
			MethodName: "CreatePromotion",
			Handler:    _GamingService_CreatePromotion_Handler,
		},
		{
			MethodName: "FindPromotions",
			Handler:    _GamingService_FindPromotions_Handler,
		},
		{
			MethodName: "FindOnePromotion",
			Handler:    _GamingService_FindOnePromotion_Handler,
		},
		{
			MethodName: "UpdatePromotion",
			Handler:    _GamingService_UpdatePromotion_Handler,
		},
		{
			MethodName: "RemovePromotion",
			Handler:    _GamingService_RemovePromotion_Handler,
		},
		{
			MethodName: "HandleCasinoBonus",
			Handler:    _GamingService_HandleCasinoBonus_Handler,
		},
		{
			MethodName: "AddGameKeys",
			Handler:    _GamingService_AddGameKeys_Handler,
		},
		{
			MethodName: "fetchGameKeys",
			Handler:    _GamingService_FetchGameKeys_Handler,
		},
		{
			MethodName: "deleteGameKeys",
			Handler:    _GamingService_DeleteGameKeys_Handler,
		},
		{
			MethodName: "fetchBonusGames",
			Handler:    _GamingService_FetchBonusGames_Handler,
		},
		{
			MethodName: "HandleCasinoJackpot",
			Handler:    _GamingService_HandleCasinoJackpot_Handler,
		},
		{
			MethodName: "HandleCasinoJackpotWinners",
			Handler:    _GamingService_HandleCasinoJackpotWinners_Handler,
		},
		{
			MethodName: "StartGame",
			Handler:    _GamingService_StartGame_Handler,
		},
		{
			MethodName: "QtechLobby",
			Handler:    _GamingService_QtechLobby_Handler,
		},
		{
			MethodName: "HandleCallback",
			Handler:    _GamingService_HandleCallback_Handler,
		},
		{
			MethodName: "HandleQtechCallback",
			Handler:    _GamingService_HandleQtechCallback_Handler,
		},
		{
			MethodName: "HandleSpribeCallback",
			Handler:    _GamingService_HandleSpribeCallback_Handler,
		},
		{
			MethodName: "HandleSmatVirtualCallback",
			Handler:    _GamingService_HandleSmatVirtualCallback_Handler,
		},
		{
			MethodName: "XpressLogin",
			Handler:    _GamingService_XpressLogin_Handler,
		},
		{
			MethodName: "XpressBalance",
			Handler:    _GamingService_XpressBalance_Handler,
		},
		{
			MethodName: "XpressDebit",
			Handler:    _GamingService_XpressDebit_Handler,
		},
		{
			MethodName: "XpressCredit",
			Handler:    _GamingService_XpressCredit_Handler,
		},
		{
			MethodName: "XpressRollback",
			Handler:    _GamingService_XpressRollback_Handler,
		},
		{
			MethodName: "XpressLogout",
			Handler:    _GamingService_XpressLogout_Handler,
		},
		{
			MethodName: "StartSmatGame",
			Handler:    _GamingService_StartSmatGame_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryGames",
			Handler:       _GamingService_QueryGames_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gaming.proto",
}
