// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.0
// source: commission.proto

package commission

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommissionService_GetAgentUser_FullMethodName                         = "/commission.CommissionService/GetAgentUser"
	CommissionService_ListAgents_FullMethodName                           = "/commission.CommissionService/ListAgents"
	CommissionService_GetCommissionProfiles_FullMethodName                = "/commission.CommissionService/getCommissionProfiles"
	CommissionService_CreateCommissionProfile_FullMethodName              = "/commission.CommissionService/createCommissionProfile"
	CommissionService_UpdateCommissionProfile_FullMethodName              = "/commission.CommissionService/updateCommissionProfile"
	CommissionService_AssignUserCommissionProfile_FullMethodName          = "/commission.CommissionService/assignUserCommissionProfile"
	CommissionService_GetUserCommissionProfiles_FullMethodName            = "/commission.CommissionService/getUserCommissionProfiles"
	CommissionService_RemoveUserCommissionProfile_FullMethodName          = "/commission.CommissionService/removeUserCommissionProfile"
	CommissionService_GetCommissionProfile_FullMethodName                 = "/commission.CommissionService/getCommissionProfile"
	CommissionService_DeleteCommissionProfile_FullMethodName              = "/commission.CommissionService/deleteCommissionProfile"
	CommissionService_GetCommissionProfileUsers_FullMethodName            = "/commission.CommissionService/getCommissionProfileUsers"
	CommissionService_CalculateCommission_FullMethodName                  = "/commission.CommissionService/calculateCommission"
	CommissionService_PayoutCommission_FullMethodName                     = "/commission.CommissionService/payoutCommission"
	CommissionService_FlatCommission_FullMethodName                       = "/commission.CommissionService/FlatCommission"
	CommissionService_MultipleCommission_FullMethodName                   = "/commission.CommissionService/MultipleCommission"
	CommissionService_ProfitCommission_FullMethodName                     = "/commission.CommissionService/ProfitCommission"
	CommissionService_SportCommission_FullMethodName                      = "/commission.CommissionService/SportCommission"
	CommissionService_VirtualCommission_FullMethodName                    = "/commission.CommissionService/VirtualCommission"
	CommissionService_TotalCommission_FullMethodName                      = "/commission.CommissionService/TotalCommission"
	CommissionService_SportBetHistory_FullMethodName                      = "/commission.CommissionService/SportBetHistory"
	CommissionService_VirtualBetHistory_FullMethodName                    = "/commission.CommissionService/VirtualBetHistory"
	CommissionService_GetAgentsCommission_FullMethodName                  = "/commission.CommissionService/GetAgentsCommission"
	CommissionService_PaidCommission_FullMethodName                       = "/commission.CommissionService/PaidCommission"
	CommissionService_ListOneUserCommissionProfile_FullMethodName         = "/commission.CommissionService/ListOneUserCommissionProfile"
	CommissionService_Totals_FullMethodName                               = "/commission.CommissionService/Totals"
	CommissionService_DepositCommission_FullMethodName                    = "/commission.CommissionService/DepositCommission"
	CommissionService_PayoutSingleCommission_FullMethodName               = "/commission.CommissionService/PayoutSingleCommission"
	CommissionService_BetCommission_FullMethodName                        = "/commission.CommissionService/BetCommission"
	CommissionService_CreateAffiliateCommissionProfile_FullMethodName     = "/commission.CommissionService/CreateAffiliateCommissionProfile"
	CommissionService_UpdateAffiliateCommissionProfile_FullMethodName     = "/commission.CommissionService/UpdateAffiliateCommissionProfile"
	CommissionService_GetAffiliateCommissionProfiles_FullMethodName       = "/commission.CommissionService/GetAffiliateCommissionProfiles"
	CommissionService_GetAffiliateCommissionProfile_FullMethodName        = "/commission.CommissionService/GetAffiliateCommissionProfile"
	CommissionService_DeleteAffiliateCommissionProfile_FullMethodName     = "/commission.CommissionService/DeleteAffiliateCommissionProfile"
	CommissionService_AssignUserAffiliateCommissionProfile_FullMethodName = "/commission.CommissionService/AssignUserAffiliateCommissionProfile"
	CommissionService_GetUserAffiliateCommissionProfiles_FullMethodName   = "/commission.CommissionService/GetUserAffiliateCommissionProfiles"
	CommissionService_RemoveUserAffiliateCommissionProfile_FullMethodName = "/commission.CommissionService/RemoveUserAffiliateCommissionProfile"
	CommissionService_ProcessFirstDepositCommission_FullMethodName        = "/commission.CommissionService/ProcessFirstDepositCommission"
	CommissionService_ProcessRevenueShareCommission_FullMethodName        = "/commission.CommissionService/ProcessRevenueShareCommission"
	CommissionService_ProcessHybridCommission_FullMethodName              = "/commission.CommissionService/ProcessHybridCommission"
	CommissionService_ProcessTieredCommission_FullMethodName              = "/commission.CommissionService/ProcessTieredCommission"
	CommissionService_ListAssignedCommissionProfiles_FullMethodName       = "/commission.CommissionService/ListAssignedCommissionProfiles"
	CommissionService_ListAllAffiliateCommissions_FullMethodName          = "/commission.CommissionService/ListAllAffiliateCommissions"
	CommissionService_AffiliatePayOutCommissions_FullMethodName           = "/commission.CommissionService/AffiliatePayOutCommissions"
	CommissionService_SuperAgentCommission_FullMethodName                 = "/commission.CommissionService/SuperAgentCommission"
	CommissionService_PaySuperAgentCommission_FullMethodName              = "/commission.CommissionService/PaySuperAgentCommission"
	CommissionService_SuperAgentData_FullMethodName                       = "/commission.CommissionService/SuperAgentData"
	CommissionService_SuperAgentTotals_FullMethodName                     = "/commission.CommissionService/SuperAgentTotals"
)

// CommissionServiceClient is the client API for CommissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommissionServiceClient interface {
	GetAgentUser(ctx context.Context, in *GetAgentUserRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	ListAgents(ctx context.Context, in *GetAgentUsersRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetCommissionProfiles(ctx context.Context, in *GetCommissionsRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	CreateCommissionProfile(ctx context.Context, in *CommissionProfile, opts ...grpc.CallOption) (*CommonResponseObj, error)
	UpdateCommissionProfile(ctx context.Context, in *CommissionProfile, opts ...grpc.CallOption) (*CommonResponseObj, error)
	AssignUserCommissionProfile(ctx context.Context, in *AssignUserCommissionProfile, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetUserCommissionProfiles(ctx context.Context, in *SingleItemRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	RemoveUserCommissionProfile(ctx context.Context, in *AssignUserCommissionProfile, opts ...grpc.CallOption) (*CommonResponseArray, error)
	GetCommissionProfile(ctx context.Context, in *SingleItemRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	DeleteCommissionProfile(ctx context.Context, in *SingleItemRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetCommissionProfileUsers(ctx context.Context, in *GetCommissionsRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	CalculateCommission(ctx context.Context, in *CalculateCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	PayoutCommission(ctx context.Context, in *PayoutCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	FlatCommission(ctx context.Context, in *FlatCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	MultipleCommission(ctx context.Context, in *CalculateCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	ProfitCommission(ctx context.Context, in *PayoutCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SportCommission(ctx context.Context, in *GetCommissionsRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error)
	VirtualCommission(ctx context.Context, in *GetCommissionsRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error)
	TotalCommission(ctx context.Context, in *GetCommissionsRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SportBetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	VirtualBetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetAgentsCommission(ctx context.Context, in *GetCommissionsRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error)
	PaidCommission(ctx context.Context, in *PaidCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	ListOneUserCommissionProfile(ctx context.Context, in *UserCommissionData, opts ...grpc.CallOption) (*CommonResponseObj, error)
	Totals(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	DepositCommission(ctx context.Context, in *DepositCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	PayoutSingleCommission(ctx context.Context, in *PayoutCommissionRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error)
	BetCommission(ctx context.Context, in *BetCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	CreateAffiliateCommissionProfile(ctx context.Context, in *AffiliateCommission, opts ...grpc.CallOption) (*CommonResponseObj, error)
	UpdateAffiliateCommissionProfile(ctx context.Context, in *AffiliateCommission, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetAffiliateCommissionProfiles(ctx context.Context, in *GetCommissionsRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	GetAffiliateCommissionProfile(ctx context.Context, in *Getdata, opts ...grpc.CallOption) (*CommonResponseObj, error)
	DeleteAffiliateCommissionProfile(ctx context.Context, in *Getdata, opts ...grpc.CallOption) (*CommonResponseObj, error)
	AssignUserAffiliateCommissionProfile(ctx context.Context, in *AssignUserCommissionProfile, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetUserAffiliateCommissionProfiles(ctx context.Context, in *Getdata, opts ...grpc.CallOption) (*CommonResponseArray, error)
	RemoveUserAffiliateCommissionProfile(ctx context.Context, in *RemoveAffiliatePayload, opts ...grpc.CallOption) (*CommonResponseObj, error)
	ProcessFirstDepositCommission(ctx context.Context, in *AffiliateIds, opts ...grpc.CallOption) (*CommonResponseArray, error)
	ProcessRevenueShareCommission(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	ProcessHybridCommission(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	ProcessTieredCommission(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	ListAssignedCommissionProfiles(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	ListAllAffiliateCommissions(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	AffiliatePayOutCommissions(ctx context.Context, in *PayoutRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	SuperAgentCommission(ctx context.Context, in *GetCommissionsRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error)
	PaySuperAgentCommission(ctx context.Context, in *SuperAgentCommissionData, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SuperAgentData(ctx context.Context, in *SuperAgentDataRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SuperAgentTotals(ctx context.Context, in *SuperAgentTotalsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
}

type commissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommissionServiceClient(cc grpc.ClientConnInterface) CommissionServiceClient {
	return &commissionServiceClient{cc}
}

func (c *commissionServiceClient) GetAgentUser(ctx context.Context, in *GetAgentUserRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, CommissionService_GetAgentUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) ListAgents(ctx context.Context, in *GetAgentUsersRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) GetCommissionProfiles(ctx context.Context, in *GetCommissionsRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, CommissionService_GetCommissionProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) CreateCommissionProfile(ctx context.Context, in *CommissionProfile, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_CreateCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) UpdateCommissionProfile(ctx context.Context, in *CommissionProfile, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_UpdateCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) AssignUserCommissionProfile(ctx context.Context, in *AssignUserCommissionProfile, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_AssignUserCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) GetUserCommissionProfiles(ctx context.Context, in *SingleItemRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, CommissionService_GetUserCommissionProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) RemoveUserCommissionProfile(ctx context.Context, in *AssignUserCommissionProfile, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, CommissionService_RemoveUserCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) GetCommissionProfile(ctx context.Context, in *SingleItemRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_GetCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) DeleteCommissionProfile(ctx context.Context, in *SingleItemRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_DeleteCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) GetCommissionProfileUsers(ctx context.Context, in *GetCommissionsRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, CommissionService_GetCommissionProfileUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) CalculateCommission(ctx context.Context, in *CalculateCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_CalculateCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) PayoutCommission(ctx context.Context, in *PayoutCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_PayoutCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) FlatCommission(ctx context.Context, in *FlatCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_FlatCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) MultipleCommission(ctx context.Context, in *CalculateCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_MultipleCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) ProfitCommission(ctx context.Context, in *PayoutCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_ProfitCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) SportCommission(ctx context.Context, in *GetCommissionsRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_SportCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) VirtualCommission(ctx context.Context, in *GetCommissionsRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_VirtualCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) TotalCommission(ctx context.Context, in *GetCommissionsRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_TotalCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) SportBetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_SportBetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) VirtualBetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_VirtualBetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) GetAgentsCommission(ctx context.Context, in *GetCommissionsRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_GetAgentsCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) PaidCommission(ctx context.Context, in *PaidCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_PaidCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) ListOneUserCommissionProfile(ctx context.Context, in *UserCommissionData, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_ListOneUserCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) Totals(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, CommissionService_Totals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) DepositCommission(ctx context.Context, in *DepositCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_DepositCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) PayoutSingleCommission(ctx context.Context, in *PayoutCommissionRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_PayoutSingleCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) BetCommission(ctx context.Context, in *BetCommissionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_BetCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) CreateAffiliateCommissionProfile(ctx context.Context, in *AffiliateCommission, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_CreateAffiliateCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) UpdateAffiliateCommissionProfile(ctx context.Context, in *AffiliateCommission, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_UpdateAffiliateCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) GetAffiliateCommissionProfiles(ctx context.Context, in *GetCommissionsRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, CommissionService_GetAffiliateCommissionProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) GetAffiliateCommissionProfile(ctx context.Context, in *Getdata, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_GetAffiliateCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) DeleteAffiliateCommissionProfile(ctx context.Context, in *Getdata, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_DeleteAffiliateCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) AssignUserAffiliateCommissionProfile(ctx context.Context, in *AssignUserCommissionProfile, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_AssignUserAffiliateCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) GetUserAffiliateCommissionProfiles(ctx context.Context, in *Getdata, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, CommissionService_GetUserAffiliateCommissionProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) RemoveUserAffiliateCommissionProfile(ctx context.Context, in *RemoveAffiliatePayload, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_RemoveUserAffiliateCommissionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) ProcessFirstDepositCommission(ctx context.Context, in *AffiliateIds, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, CommissionService_ProcessFirstDepositCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) ProcessRevenueShareCommission(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, CommissionService_ProcessRevenueShareCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) ProcessHybridCommission(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_ProcessHybridCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) ProcessTieredCommission(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_ProcessTieredCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) ListAssignedCommissionProfiles(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_ListAssignedCommissionProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) ListAllAffiliateCommissions(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_ListAllAffiliateCommissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) AffiliatePayOutCommissions(ctx context.Context, in *PayoutRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, CommissionService_AffiliatePayOutCommissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) SuperAgentCommission(ctx context.Context, in *GetCommissionsRequestData, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_SuperAgentCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) PaySuperAgentCommission(ctx context.Context, in *SuperAgentCommissionData, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_PaySuperAgentCommission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) SuperAgentData(ctx context.Context, in *SuperAgentDataRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_SuperAgentData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commissionServiceClient) SuperAgentTotals(ctx context.Context, in *SuperAgentTotalsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, CommissionService_SuperAgentTotals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommissionServiceServer is the server API for CommissionService service.
// All implementations must embed UnimplementedCommissionServiceServer
// for forward compatibility.
type CommissionServiceServer interface {
	GetAgentUser(context.Context, *GetAgentUserRequest) (*CommonResponseArray, error)
	ListAgents(context.Context, *GetAgentUsersRequest) (*CommonResponseObj, error)
	GetCommissionProfiles(context.Context, *GetCommissionsRequest) (*CommonResponseArray, error)
	CreateCommissionProfile(context.Context, *CommissionProfile) (*CommonResponseObj, error)
	UpdateCommissionProfile(context.Context, *CommissionProfile) (*CommonResponseObj, error)
	AssignUserCommissionProfile(context.Context, *AssignUserCommissionProfile) (*CommonResponseObj, error)
	GetUserCommissionProfiles(context.Context, *SingleItemRequest) (*CommonResponseArray, error)
	RemoveUserCommissionProfile(context.Context, *AssignUserCommissionProfile) (*CommonResponseArray, error)
	GetCommissionProfile(context.Context, *SingleItemRequest) (*CommonResponseObj, error)
	DeleteCommissionProfile(context.Context, *SingleItemRequest) (*CommonResponseObj, error)
	GetCommissionProfileUsers(context.Context, *GetCommissionsRequest) (*CommonResponseArray, error)
	CalculateCommission(context.Context, *CalculateCommissionRequest) (*CommonResponseObj, error)
	PayoutCommission(context.Context, *PayoutCommissionRequest) (*CommonResponseObj, error)
	FlatCommission(context.Context, *FlatCommissionRequest) (*CommonResponseObj, error)
	MultipleCommission(context.Context, *CalculateCommissionRequest) (*CommonResponseObj, error)
	ProfitCommission(context.Context, *PayoutCommissionRequest) (*CommonResponseObj, error)
	SportCommission(context.Context, *GetCommissionsRequestData) (*CommonResponseObj, error)
	VirtualCommission(context.Context, *GetCommissionsRequestData) (*CommonResponseObj, error)
	TotalCommission(context.Context, *GetCommissionsRequestData) (*CommonResponseObj, error)
	SportBetHistory(context.Context, *BetHistoryRequest) (*CommonResponseObj, error)
	VirtualBetHistory(context.Context, *BetHistoryRequest) (*CommonResponseObj, error)
	GetAgentsCommission(context.Context, *GetCommissionsRequestData) (*CommonResponseObj, error)
	PaidCommission(context.Context, *PaidCommissionRequest) (*CommonResponseObj, error)
	ListOneUserCommissionProfile(context.Context, *UserCommissionData) (*CommonResponseObj, error)
	Totals(context.Context, *SalesReportRequest) (*CommonResponseArray, error)
	DepositCommission(context.Context, *DepositCommissionRequest) (*CommonResponseObj, error)
	PayoutSingleCommission(context.Context, *PayoutCommissionRequestData) (*CommonResponseObj, error)
	BetCommission(context.Context, *BetCommissionRequest) (*CommonResponseObj, error)
	CreateAffiliateCommissionProfile(context.Context, *AffiliateCommission) (*CommonResponseObj, error)
	UpdateAffiliateCommissionProfile(context.Context, *AffiliateCommission) (*CommonResponseObj, error)
	GetAffiliateCommissionProfiles(context.Context, *GetCommissionsRequest) (*CommonResponseArray, error)
	GetAffiliateCommissionProfile(context.Context, *Getdata) (*CommonResponseObj, error)
	DeleteAffiliateCommissionProfile(context.Context, *Getdata) (*CommonResponseObj, error)
	AssignUserAffiliateCommissionProfile(context.Context, *AssignUserCommissionProfile) (*CommonResponseObj, error)
	GetUserAffiliateCommissionProfiles(context.Context, *Getdata) (*CommonResponseArray, error)
	RemoveUserAffiliateCommissionProfile(context.Context, *RemoveAffiliatePayload) (*CommonResponseObj, error)
	ProcessFirstDepositCommission(context.Context, *AffiliateIds) (*CommonResponseArray, error)
	ProcessRevenueShareCommission(context.Context, *PaymentRequest) (*CommonResponseArray, error)
	ProcessHybridCommission(context.Context, *PaymentRequest) (*CommonResponseObj, error)
	ProcessTieredCommission(context.Context, *PaymentRequest) (*CommonResponseObj, error)
	ListAssignedCommissionProfiles(context.Context, *ClientRequest) (*CommonResponseObj, error)
	ListAllAffiliateCommissions(context.Context, *ClientRequest) (*CommonResponseObj, error)
	AffiliatePayOutCommissions(context.Context, *PayoutRequest) (*CommonResponseArray, error)
	SuperAgentCommission(context.Context, *GetCommissionsRequestData) (*CommonResponseObj, error)
	PaySuperAgentCommission(context.Context, *SuperAgentCommissionData) (*CommonResponseObj, error)
	SuperAgentData(context.Context, *SuperAgentDataRequest) (*CommonResponseObj, error)
	SuperAgentTotals(context.Context, *SuperAgentTotalsRequest) (*CommonResponseObj, error)
	mustEmbedUnimplementedCommissionServiceServer()
}

// UnimplementedCommissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommissionServiceServer struct{}

func (UnimplementedCommissionServiceServer) GetAgentUser(context.Context, *GetAgentUserRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentUser not implemented")
}
func (UnimplementedCommissionServiceServer) ListAgents(context.Context, *GetAgentUsersRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedCommissionServiceServer) GetCommissionProfiles(context.Context, *GetCommissionsRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommissionProfiles not implemented")
}
func (UnimplementedCommissionServiceServer) CreateCommissionProfile(context.Context, *CommissionProfile) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) UpdateCommissionProfile(context.Context, *CommissionProfile) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) AssignUserCommissionProfile(context.Context, *AssignUserCommissionProfile) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignUserCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) GetUserCommissionProfiles(context.Context, *SingleItemRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCommissionProfiles not implemented")
}
func (UnimplementedCommissionServiceServer) RemoveUserCommissionProfile(context.Context, *AssignUserCommissionProfile) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) GetCommissionProfile(context.Context, *SingleItemRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) DeleteCommissionProfile(context.Context, *SingleItemRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) GetCommissionProfileUsers(context.Context, *GetCommissionsRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommissionProfileUsers not implemented")
}
func (UnimplementedCommissionServiceServer) CalculateCommission(context.Context, *CalculateCommissionRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateCommission not implemented")
}
func (UnimplementedCommissionServiceServer) PayoutCommission(context.Context, *PayoutCommissionRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method PayoutCommission not implemented")
}
func (UnimplementedCommissionServiceServer) FlatCommission(context.Context, *FlatCommissionRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method FlatCommission not implemented")
}
func (UnimplementedCommissionServiceServer) MultipleCommission(context.Context, *CalculateCommissionRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method MultipleCommission not implemented")
}
func (UnimplementedCommissionServiceServer) ProfitCommission(context.Context, *PayoutCommissionRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method ProfitCommission not implemented")
}
func (UnimplementedCommissionServiceServer) SportCommission(context.Context, *GetCommissionsRequestData) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method SportCommission not implemented")
}
func (UnimplementedCommissionServiceServer) VirtualCommission(context.Context, *GetCommissionsRequestData) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method VirtualCommission not implemented")
}
func (UnimplementedCommissionServiceServer) TotalCommission(context.Context, *GetCommissionsRequestData) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method TotalCommission not implemented")
}
func (UnimplementedCommissionServiceServer) SportBetHistory(context.Context, *BetHistoryRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method SportBetHistory not implemented")
}
func (UnimplementedCommissionServiceServer) VirtualBetHistory(context.Context, *BetHistoryRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method VirtualBetHistory not implemented")
}
func (UnimplementedCommissionServiceServer) GetAgentsCommission(context.Context, *GetCommissionsRequestData) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentsCommission not implemented")
}
func (UnimplementedCommissionServiceServer) PaidCommission(context.Context, *PaidCommissionRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method PaidCommission not implemented")
}
func (UnimplementedCommissionServiceServer) ListOneUserCommissionProfile(context.Context, *UserCommissionData) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOneUserCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) Totals(context.Context, *SalesReportRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method Totals not implemented")
}
func (UnimplementedCommissionServiceServer) DepositCommission(context.Context, *DepositCommissionRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method DepositCommission not implemented")
}
func (UnimplementedCommissionServiceServer) PayoutSingleCommission(context.Context, *PayoutCommissionRequestData) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method PayoutSingleCommission not implemented")
}
func (UnimplementedCommissionServiceServer) BetCommission(context.Context, *BetCommissionRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method BetCommission not implemented")
}
func (UnimplementedCommissionServiceServer) CreateAffiliateCommissionProfile(context.Context, *AffiliateCommission) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAffiliateCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) UpdateAffiliateCommissionProfile(context.Context, *AffiliateCommission) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAffiliateCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) GetAffiliateCommissionProfiles(context.Context, *GetCommissionsRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAffiliateCommissionProfiles not implemented")
}
func (UnimplementedCommissionServiceServer) GetAffiliateCommissionProfile(context.Context, *Getdata) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAffiliateCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) DeleteAffiliateCommissionProfile(context.Context, *Getdata) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAffiliateCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) AssignUserAffiliateCommissionProfile(context.Context, *AssignUserCommissionProfile) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignUserAffiliateCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) GetUserAffiliateCommissionProfiles(context.Context, *Getdata) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAffiliateCommissionProfiles not implemented")
}
func (UnimplementedCommissionServiceServer) RemoveUserAffiliateCommissionProfile(context.Context, *RemoveAffiliatePayload) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserAffiliateCommissionProfile not implemented")
}
func (UnimplementedCommissionServiceServer) ProcessFirstDepositCommission(context.Context, *AffiliateIds) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessFirstDepositCommission not implemented")
}
func (UnimplementedCommissionServiceServer) ProcessRevenueShareCommission(context.Context, *PaymentRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessRevenueShareCommission not implemented")
}
func (UnimplementedCommissionServiceServer) ProcessHybridCommission(context.Context, *PaymentRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessHybridCommission not implemented")
}
func (UnimplementedCommissionServiceServer) ProcessTieredCommission(context.Context, *PaymentRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessTieredCommission not implemented")
}
func (UnimplementedCommissionServiceServer) ListAssignedCommissionProfiles(context.Context, *ClientRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssignedCommissionProfiles not implemented")
}
func (UnimplementedCommissionServiceServer) ListAllAffiliateCommissions(context.Context, *ClientRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllAffiliateCommissions not implemented")
}
func (UnimplementedCommissionServiceServer) AffiliatePayOutCommissions(context.Context, *PayoutRequest) (*CommonResponseArray, error) {
	return nil, status.Error(codes.Unimplemented, "method AffiliatePayOutCommissions not implemented")
}
func (UnimplementedCommissionServiceServer) SuperAgentCommission(context.Context, *GetCommissionsRequestData) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method SuperAgentCommission not implemented")
}
func (UnimplementedCommissionServiceServer) PaySuperAgentCommission(context.Context, *SuperAgentCommissionData) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method PaySuperAgentCommission not implemented")
}
func (UnimplementedCommissionServiceServer) SuperAgentData(context.Context, *SuperAgentDataRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method SuperAgentData not implemented")
}
func (UnimplementedCommissionServiceServer) SuperAgentTotals(context.Context, *SuperAgentTotalsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method SuperAgentTotals not implemented")
}
func (UnimplementedCommissionServiceServer) mustEmbedUnimplementedCommissionServiceServer() {}
func (UnimplementedCommissionServiceServer) testEmbeddedByValue()                           {}

// UnsafeCommissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommissionServiceServer will
// result in compilation errors.
type UnsafeCommissionServiceServer interface {
	mustEmbedUnimplementedCommissionServiceServer()
}

func RegisterCommissionServiceServer(s grpc.ServiceRegistrar, srv CommissionServiceServer) {
	// If the following call panics, it indicates UnimplementedCommissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommissionService_ServiceDesc, srv)
}

func _CommissionService_GetAgentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).GetAgentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_GetAgentUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).GetAgentUser(ctx, req.(*GetAgentUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).ListAgents(ctx, req.(*GetAgentUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_GetCommissionProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).GetCommissionProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_GetCommissionProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).GetCommissionProfiles(ctx, req.(*GetCommissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_CreateCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommissionProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).CreateCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_CreateCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).CreateCommissionProfile(ctx, req.(*CommissionProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_UpdateCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommissionProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).UpdateCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_UpdateCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).UpdateCommissionProfile(ctx, req.(*CommissionProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_AssignUserCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignUserCommissionProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).AssignUserCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_AssignUserCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).AssignUserCommissionProfile(ctx, req.(*AssignUserCommissionProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_GetUserCommissionProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).GetUserCommissionProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_GetUserCommissionProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).GetUserCommissionProfiles(ctx, req.(*SingleItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_RemoveUserCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignUserCommissionProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).RemoveUserCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_RemoveUserCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).RemoveUserCommissionProfile(ctx, req.(*AssignUserCommissionProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_GetCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).GetCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_GetCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).GetCommissionProfile(ctx, req.(*SingleItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_DeleteCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).DeleteCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_DeleteCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).DeleteCommissionProfile(ctx, req.(*SingleItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_GetCommissionProfileUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).GetCommissionProfileUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_GetCommissionProfileUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).GetCommissionProfileUsers(ctx, req.(*GetCommissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_CalculateCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).CalculateCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_CalculateCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).CalculateCommission(ctx, req.(*CalculateCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_PayoutCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayoutCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).PayoutCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_PayoutCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).PayoutCommission(ctx, req.(*PayoutCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_FlatCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlatCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).FlatCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_FlatCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).FlatCommission(ctx, req.(*FlatCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_MultipleCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).MultipleCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_MultipleCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).MultipleCommission(ctx, req.(*CalculateCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_ProfitCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayoutCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).ProfitCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_ProfitCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).ProfitCommission(ctx, req.(*PayoutCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_SportCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommissionsRequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).SportCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_SportCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).SportCommission(ctx, req.(*GetCommissionsRequestData))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_VirtualCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommissionsRequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).VirtualCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_VirtualCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).VirtualCommission(ctx, req.(*GetCommissionsRequestData))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_TotalCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommissionsRequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).TotalCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_TotalCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).TotalCommission(ctx, req.(*GetCommissionsRequestData))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_SportBetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).SportBetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_SportBetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).SportBetHistory(ctx, req.(*BetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_VirtualBetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).VirtualBetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_VirtualBetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).VirtualBetHistory(ctx, req.(*BetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_GetAgentsCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommissionsRequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).GetAgentsCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_GetAgentsCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).GetAgentsCommission(ctx, req.(*GetCommissionsRequestData))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_PaidCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaidCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).PaidCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_PaidCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).PaidCommission(ctx, req.(*PaidCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_ListOneUserCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCommissionData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).ListOneUserCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_ListOneUserCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).ListOneUserCommissionProfile(ctx, req.(*UserCommissionData))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_Totals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).Totals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_Totals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).Totals(ctx, req.(*SalesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_DepositCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).DepositCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_DepositCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).DepositCommission(ctx, req.(*DepositCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_PayoutSingleCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayoutCommissionRequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).PayoutSingleCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_PayoutSingleCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).PayoutSingleCommission(ctx, req.(*PayoutCommissionRequestData))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_BetCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).BetCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_BetCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).BetCommission(ctx, req.(*BetCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_CreateAffiliateCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AffiliateCommission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).CreateAffiliateCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_CreateAffiliateCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).CreateAffiliateCommissionProfile(ctx, req.(*AffiliateCommission))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_UpdateAffiliateCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AffiliateCommission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).UpdateAffiliateCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_UpdateAffiliateCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).UpdateAffiliateCommissionProfile(ctx, req.(*AffiliateCommission))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_GetAffiliateCommissionProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).GetAffiliateCommissionProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_GetAffiliateCommissionProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).GetAffiliateCommissionProfiles(ctx, req.(*GetCommissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_GetAffiliateCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Getdata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).GetAffiliateCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_GetAffiliateCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).GetAffiliateCommissionProfile(ctx, req.(*Getdata))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_DeleteAffiliateCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Getdata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).DeleteAffiliateCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_DeleteAffiliateCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).DeleteAffiliateCommissionProfile(ctx, req.(*Getdata))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_AssignUserAffiliateCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignUserCommissionProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).AssignUserAffiliateCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_AssignUserAffiliateCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).AssignUserAffiliateCommissionProfile(ctx, req.(*AssignUserCommissionProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_GetUserAffiliateCommissionProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Getdata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).GetUserAffiliateCommissionProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_GetUserAffiliateCommissionProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).GetUserAffiliateCommissionProfiles(ctx, req.(*Getdata))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_RemoveUserAffiliateCommissionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAffiliatePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).RemoveUserAffiliateCommissionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_RemoveUserAffiliateCommissionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).RemoveUserAffiliateCommissionProfile(ctx, req.(*RemoveAffiliatePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_ProcessFirstDepositCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AffiliateIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).ProcessFirstDepositCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_ProcessFirstDepositCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).ProcessFirstDepositCommission(ctx, req.(*AffiliateIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_ProcessRevenueShareCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).ProcessRevenueShareCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_ProcessRevenueShareCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).ProcessRevenueShareCommission(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_ProcessHybridCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).ProcessHybridCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_ProcessHybridCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).ProcessHybridCommission(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_ProcessTieredCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).ProcessTieredCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_ProcessTieredCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).ProcessTieredCommission(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_ListAssignedCommissionProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).ListAssignedCommissionProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_ListAssignedCommissionProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).ListAssignedCommissionProfiles(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_ListAllAffiliateCommissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).ListAllAffiliateCommissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_ListAllAffiliateCommissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).ListAllAffiliateCommissions(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_AffiliatePayOutCommissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).AffiliatePayOutCommissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_AffiliatePayOutCommissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).AffiliatePayOutCommissions(ctx, req.(*PayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_SuperAgentCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommissionsRequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).SuperAgentCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_SuperAgentCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).SuperAgentCommission(ctx, req.(*GetCommissionsRequestData))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_PaySuperAgentCommission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuperAgentCommissionData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).PaySuperAgentCommission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_PaySuperAgentCommission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).PaySuperAgentCommission(ctx, req.(*SuperAgentCommissionData))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_SuperAgentData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuperAgentDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).SuperAgentData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_SuperAgentData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).SuperAgentData(ctx, req.(*SuperAgentDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommissionService_SuperAgentTotals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuperAgentTotalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommissionServiceServer).SuperAgentTotals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommissionService_SuperAgentTotals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommissionServiceServer).SuperAgentTotals(ctx, req.(*SuperAgentTotalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommissionService_ServiceDesc is the grpc.ServiceDesc for CommissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commission.CommissionService",
	HandlerType: (*CommissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgentUser",
			Handler:    _CommissionService_GetAgentUser_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _CommissionService_ListAgents_Handler,
		},
		{
			MethodName: "getCommissionProfiles",
			Handler:    _CommissionService_GetCommissionProfiles_Handler,
		},
		{
			MethodName: "createCommissionProfile",
			Handler:    _CommissionService_CreateCommissionProfile_Handler,
		},
		{
			MethodName: "updateCommissionProfile",
			Handler:    _CommissionService_UpdateCommissionProfile_Handler,
		},
		{
			MethodName: "assignUserCommissionProfile",
			Handler:    _CommissionService_AssignUserCommissionProfile_Handler,
		},
		{
			MethodName: "getUserCommissionProfiles",
			Handler:    _CommissionService_GetUserCommissionProfiles_Handler,
		},
		{
			MethodName: "removeUserCommissionProfile",
			Handler:    _CommissionService_RemoveUserCommissionProfile_Handler,
		},
		{
			MethodName: "getCommissionProfile",
			Handler:    _CommissionService_GetCommissionProfile_Handler,
		},
		{
			MethodName: "deleteCommissionProfile",
			Handler:    _CommissionService_DeleteCommissionProfile_Handler,
		},
		{
			MethodName: "getCommissionProfileUsers",
			Handler:    _CommissionService_GetCommissionProfileUsers_Handler,
		},
		{
			MethodName: "calculateCommission",
			Handler:    _CommissionService_CalculateCommission_Handler,
		},
		{
			MethodName: "payoutCommission",
			Handler:    _CommissionService_PayoutCommission_Handler,
		},
		{
			MethodName: "FlatCommission",
			Handler:    _CommissionService_FlatCommission_Handler,
		},
		{
			MethodName: "MultipleCommission",
			Handler:    _CommissionService_MultipleCommission_Handler,
		},
		{
			MethodName: "ProfitCommission",
			Handler:    _CommissionService_ProfitCommission_Handler,
		},
		{
			MethodName: "SportCommission",
			Handler:    _CommissionService_SportCommission_Handler,
		},
		{
			MethodName: "VirtualCommission",
			Handler:    _CommissionService_VirtualCommission_Handler,
		},
		{
			MethodName: "TotalCommission",
			Handler:    _CommissionService_TotalCommission_Handler,
		},
		{
			MethodName: "SportBetHistory",
			Handler:    _CommissionService_SportBetHistory_Handler,
		},
		{
			MethodName: "VirtualBetHistory",
			Handler:    _CommissionService_VirtualBetHistory_Handler,
		},
		{
			MethodName: "GetAgentsCommission",
			Handler:    _CommissionService_GetAgentsCommission_Handler,
		},
		{
			MethodName: "PaidCommission",
			Handler:    _CommissionService_PaidCommission_Handler,
		},
		{
			MethodName: "ListOneUserCommissionProfile",
			Handler:    _CommissionService_ListOneUserCommissionProfile_Handler,
		},
		{
			MethodName: "Totals",
			Handler:    _CommissionService_Totals_Handler,
		},
		{
			MethodName: "DepositCommission",
			Handler:    _CommissionService_DepositCommission_Handler,
		},
		{
			MethodName: "PayoutSingleCommission",
			Handler:    _CommissionService_PayoutSingleCommission_Handler,
		},
		{
			MethodName: "BetCommission",
			Handler:    _CommissionService_BetCommission_Handler,
		},
		{
			MethodName: "CreateAffiliateCommissionProfile",
			Handler:    _CommissionService_CreateAffiliateCommissionProfile_Handler,
		},
		{
			MethodName: "UpdateAffiliateCommissionProfile",
			Handler:    _CommissionService_UpdateAffiliateCommissionProfile_Handler,
		},
		{
			MethodName: "GetAffiliateCommissionProfiles",
			Handler:    _CommissionService_GetAffiliateCommissionProfiles_Handler,
		},
		{
			MethodName: "GetAffiliateCommissionProfile",
			Handler:    _CommissionService_GetAffiliateCommissionProfile_Handler,
		},
		{
			MethodName: "DeleteAffiliateCommissionProfile",
			Handler:    _CommissionService_DeleteAffiliateCommissionProfile_Handler,
		},
		{
			MethodName: "AssignUserAffiliateCommissionProfile",
			Handler:    _CommissionService_AssignUserAffiliateCommissionProfile_Handler,
		},
		{
			MethodName: "GetUserAffiliateCommissionProfiles",
			Handler:    _CommissionService_GetUserAffiliateCommissionProfiles_Handler,
		},
		{
			MethodName: "RemoveUserAffiliateCommissionProfile",
			Handler:    _CommissionService_RemoveUserAffiliateCommissionProfile_Handler,
		},
		{
			MethodName: "ProcessFirstDepositCommission",
			Handler:    _CommissionService_ProcessFirstDepositCommission_Handler,
		},
		{
			MethodName: "ProcessRevenueShareCommission",
			Handler:    _CommissionService_ProcessRevenueShareCommission_Handler,
		},
		{
			MethodName: "ProcessHybridCommission",
			Handler:    _CommissionService_ProcessHybridCommission_Handler,
		},
		{
			MethodName: "ProcessTieredCommission",
			Handler:    _CommissionService_ProcessTieredCommission_Handler,
		},
		{
			MethodName: "ListAssignedCommissionProfiles",
			Handler:    _CommissionService_ListAssignedCommissionProfiles_Handler,
		},
		{
			MethodName: "ListAllAffiliateCommissions",
			Handler:    _CommissionService_ListAllAffiliateCommissions_Handler,
		},
		{
			MethodName: "AffiliatePayOutCommissions",
			Handler:    _CommissionService_AffiliatePayOutCommissions_Handler,
		},
		{
			MethodName: "SuperAgentCommission",
			Handler:    _CommissionService_SuperAgentCommission_Handler,
		},
		{
			MethodName: "PaySuperAgentCommission",
			Handler:    _CommissionService_PaySuperAgentCommission_Handler,
		},
		{
			MethodName: "SuperAgentData",
			Handler:    _CommissionService_SuperAgentData_Handler,
		},
		{
			MethodName: "SuperAgentTotals",
			Handler:    _CommissionService_SuperAgentTotals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commission.proto",
}
