// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.0
// source: noti.proto

package noti

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_SetReadNotifications_FullMethodName = "/notification.NotificationService/SetReadNotifications"
	NotificationService_GetUserNotifications_FullMethodName = "/notification.NotificationService/GetUserNotifications"
	NotificationService_HandleNotifications_FullMethodName  = "/notification.NotificationService/HandleNotifications"
	NotificationService_SaveSettings_FullMethodName         = "/notification.NotificationService/SaveSettings"
	NotificationService_GetSettings_FullMethodName          = "/notification.NotificationService/GetSettings"
	NotificationService_SendSms_FullMethodName              = "/notification.NotificationService/SendSms"
	NotificationService_SendOtp_FullMethodName              = "/notification.NotificationService/SendOtp"
	NotificationService_VerifyOtp_FullMethodName            = "/notification.NotificationService/verifyOtp"
	NotificationService_GetDeliveryReport_FullMethodName    = "/notification.NotificationService/GetDeliveryReport"
	NotificationService_FindOneMessage_FullMethodName       = "/notification.NotificationService/findOneMessage"
	NotificationService_FindAllMessages_FullMethodName      = "/notification.NotificationService/FindAllMessages"
	NotificationService_UpdateMessage_FullMethodName        = "/notification.NotificationService/updateMessage"
	NotificationService_DeleteMessage_FullMethodName        = "/notification.NotificationService/deleteMessage"
	NotificationService_CreateMessage_FullMethodName        = "/notification.NotificationService/createMessage"
	NotificationService_SendMessage_FullMethodName          = "/notification.NotificationService/sendMessage"
	NotificationService_FindUserMessages_FullMethodName     = "/notification.NotificationService/findUserMessages"
	NotificationService_UpdateUserMessage_FullMethodName    = "/notification.NotificationService/updateUserMessage"
	NotificationService_DeleteUserMessage_FullMethodName    = "/notification.NotificationService/deleteUserMessage"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	SetReadNotifications(ctx context.Context, in *SetReadNotificationsRequest, opts ...grpc.CallOption) (*SetReadNotificationsResponse, error)
	GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsResponse, error)
	HandleNotifications(ctx context.Context, in *HandleNotificationsRequest, opts ...grpc.CallOption) (*HandleNotificationsResponse, error)
	SaveSettings(ctx context.Context, in *SaveSettingsRequest, opts ...grpc.CallOption) (*SaveSettingsResponse, error)
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error)
	SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error)
	SendOtp(ctx context.Context, in *SendOtpRequest, opts ...grpc.CallOption) (*SendSmsResponse, error)
	VerifyOtp(ctx context.Context, in *VerifyOtpRequest, opts ...grpc.CallOption) (*SendSmsResponse, error)
	GetDeliveryReport(ctx context.Context, in *DeliveryReportRequest, opts ...grpc.CallOption) (*DeliveryReportResponse, error)
	FindOneMessage(ctx context.Context, in *FindOneMessage, opts ...grpc.CallOption) (*CommonResponseObj, error)
	FindAllMessages(ctx context.Context, in *ClientIdRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	UpdateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	DeleteMessage(ctx context.Context, in *FindOneMessage, opts ...grpc.CallOption) (*CommonResponseObj, error)
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	FindUserMessages(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	UpdateUserMessage(ctx context.Context, in *FindOneMessage, opts ...grpc.CallOption) (*CommonResponseObj, error)
	DeleteUserMessage(ctx context.Context, in *FindOneMessage, opts ...grpc.CallOption) (*CommonResponseObj, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) SetReadNotifications(ctx context.Context, in *SetReadNotificationsRequest, opts ...grpc.CallOption) (*SetReadNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetReadNotificationsResponse)
	err := c.cc.Invoke(ctx, NotificationService_SetReadNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserNotificationsResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetUserNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) HandleNotifications(ctx context.Context, in *HandleNotificationsRequest, opts ...grpc.CallOption) (*HandleNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleNotificationsResponse)
	err := c.cc.Invoke(ctx, NotificationService_HandleNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SaveSettings(ctx context.Context, in *SaveSettingsRequest, opts ...grpc.CallOption) (*SaveSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSettingsResponse)
	err := c.cc.Invoke(ctx, NotificationService_SaveSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSettingsResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSmsResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendSms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendOtp(ctx context.Context, in *SendOtpRequest, opts ...grpc.CallOption) (*SendSmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSmsResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendOtp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) VerifyOtp(ctx context.Context, in *VerifyOtpRequest, opts ...grpc.CallOption) (*SendSmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSmsResponse)
	err := c.cc.Invoke(ctx, NotificationService_VerifyOtp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetDeliveryReport(ctx context.Context, in *DeliveryReportRequest, opts ...grpc.CallOption) (*DeliveryReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryReportResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetDeliveryReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) FindOneMessage(ctx context.Context, in *FindOneMessage, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, NotificationService_FindOneMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) FindAllMessages(ctx context.Context, in *ClientIdRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, NotificationService_FindAllMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, NotificationService_UpdateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) DeleteMessage(ctx context.Context, in *FindOneMessage, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, NotificationService_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, NotificationService_CreateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, NotificationService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) FindUserMessages(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, NotificationService_FindUserMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateUserMessage(ctx context.Context, in *FindOneMessage, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, NotificationService_UpdateUserMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) DeleteUserMessage(ctx context.Context, in *FindOneMessage, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, NotificationService_DeleteUserMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	SetReadNotifications(context.Context, *SetReadNotificationsRequest) (*SetReadNotificationsResponse, error)
	GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsResponse, error)
	HandleNotifications(context.Context, *HandleNotificationsRequest) (*HandleNotificationsResponse, error)
	SaveSettings(context.Context, *SaveSettingsRequest) (*SaveSettingsResponse, error)
	GetSettings(context.Context, *GetSettingsRequest) (*GetSettingsResponse, error)
	SendSms(context.Context, *SendSmsRequest) (*SendSmsResponse, error)
	SendOtp(context.Context, *SendOtpRequest) (*SendSmsResponse, error)
	VerifyOtp(context.Context, *VerifyOtpRequest) (*SendSmsResponse, error)
	GetDeliveryReport(context.Context, *DeliveryReportRequest) (*DeliveryReportResponse, error)
	FindOneMessage(context.Context, *FindOneMessage) (*CommonResponseObj, error)
	FindAllMessages(context.Context, *ClientIdRequest) (*CommonResponseObj, error)
	UpdateMessage(context.Context, *CreateMessageRequest) (*CommonResponseObj, error)
	DeleteMessage(context.Context, *FindOneMessage) (*CommonResponseObj, error)
	CreateMessage(context.Context, *CreateMessageRequest) (*CommonResponseObj, error)
	SendMessage(context.Context, *SendMessageRequest) (*CommonResponseObj, error)
	FindUserMessages(context.Context, *GetUserNotificationsRequest) (*CommonResponseObj, error)
	UpdateUserMessage(context.Context, *FindOneMessage) (*CommonResponseObj, error)
	DeleteUserMessage(context.Context, *FindOneMessage) (*CommonResponseObj, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) SetReadNotifications(context.Context, *SetReadNotificationsRequest) (*SetReadNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetReadNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) HandleNotifications(context.Context, *HandleNotificationsRequest) (*HandleNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) SaveSettings(context.Context, *SaveSettingsRequest) (*SaveSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSettings not implemented")
}
func (UnimplementedNotificationServiceServer) GetSettings(context.Context, *GetSettingsRequest) (*GetSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedNotificationServiceServer) SendSms(context.Context, *SendSmsRequest) (*SendSmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSms not implemented")
}
func (UnimplementedNotificationServiceServer) SendOtp(context.Context, *SendOtpRequest) (*SendSmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendOtp not implemented")
}
func (UnimplementedNotificationServiceServer) VerifyOtp(context.Context, *VerifyOtpRequest) (*SendSmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyOtp not implemented")
}
func (UnimplementedNotificationServiceServer) GetDeliveryReport(context.Context, *DeliveryReportRequest) (*DeliveryReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryReport not implemented")
}
func (UnimplementedNotificationServiceServer) FindOneMessage(context.Context, *FindOneMessage) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOneMessage not implemented")
}
func (UnimplementedNotificationServiceServer) FindAllMessages(context.Context, *ClientIdRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAllMessages not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateMessage(context.Context, *CreateMessageRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMessage not implemented")
}
func (UnimplementedNotificationServiceServer) DeleteMessage(context.Context, *FindOneMessage) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedNotificationServiceServer) CreateMessage(context.Context, *CreateMessageRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedNotificationServiceServer) SendMessage(context.Context, *SendMessageRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedNotificationServiceServer) FindUserMessages(context.Context, *GetUserNotificationsRequest) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUserMessages not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateUserMessage(context.Context, *FindOneMessage) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserMessage not implemented")
}
func (UnimplementedNotificationServiceServer) DeleteUserMessage(context.Context, *FindOneMessage) (*CommonResponseObj, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserMessage not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_SetReadNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReadNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SetReadNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SetReadNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SetReadNotifications(ctx, req.(*SetReadNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetUserNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetUserNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetUserNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetUserNotifications(ctx, req.(*GetUserNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_HandleNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).HandleNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_HandleNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).HandleNotifications(ctx, req.(*HandleNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SaveSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SaveSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SaveSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SaveSettings(ctx, req.(*SaveSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendSms(ctx, req.(*SendSmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendOtp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendOtp(ctx, req.(*SendOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_VerifyOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).VerifyOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_VerifyOtp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).VerifyOtp(ctx, req.(*VerifyOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetDeliveryReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetDeliveryReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetDeliveryReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetDeliveryReport(ctx, req.(*DeliveryReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_FindOneMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).FindOneMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_FindOneMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).FindOneMessage(ctx, req.(*FindOneMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_FindAllMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).FindAllMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_FindAllMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).FindAllMessages(ctx, req.(*ClientIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UpdateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).DeleteMessage(ctx, req.(*FindOneMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_FindUserMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).FindUserMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_FindUserMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).FindUserMessages(ctx, req.(*GetUserNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateUserMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateUserMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UpdateUserMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateUserMessage(ctx, req.(*FindOneMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_DeleteUserMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).DeleteUserMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_DeleteUserMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).DeleteUserMessage(ctx, req.(*FindOneMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetReadNotifications",
			Handler:    _NotificationService_SetReadNotifications_Handler,
		},
		{
			MethodName: "GetUserNotifications",
			Handler:    _NotificationService_GetUserNotifications_Handler,
		},
		{
			MethodName: "HandleNotifications",
			Handler:    _NotificationService_HandleNotifications_Handler,
		},
		{
			MethodName: "SaveSettings",
			Handler:    _NotificationService_SaveSettings_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _NotificationService_GetSettings_Handler,
		},
		{
			MethodName: "SendSms",
			Handler:    _NotificationService_SendSms_Handler,
		},
		{
			MethodName: "SendOtp",
			Handler:    _NotificationService_SendOtp_Handler,
		},
		{
			MethodName: "verifyOtp",
			Handler:    _NotificationService_VerifyOtp_Handler,
		},
		{
			MethodName: "GetDeliveryReport",
			Handler:    _NotificationService_GetDeliveryReport_Handler,
		},
		{
			MethodName: "findOneMessage",
			Handler:    _NotificationService_FindOneMessage_Handler,
		},
		{
			MethodName: "FindAllMessages",
			Handler:    _NotificationService_FindAllMessages_Handler,
		},
		{
			MethodName: "updateMessage",
			Handler:    _NotificationService_UpdateMessage_Handler,
		},
		{
			MethodName: "deleteMessage",
			Handler:    _NotificationService_DeleteMessage_Handler,
		},
		{
			MethodName: "createMessage",
			Handler:    _NotificationService_CreateMessage_Handler,
		},
		{
			MethodName: "sendMessage",
			Handler:    _NotificationService_SendMessage_Handler,
		},
		{
			MethodName: "findUserMessages",
			Handler:    _NotificationService_FindUserMessages_Handler,
		},
		{
			MethodName: "updateUserMessage",
			Handler:    _NotificationService_UpdateUserMessage_Handler,
		},
		{
			MethodName: "deleteUserMessage",
			Handler:    _NotificationService_DeleteUserMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noti.proto",
}
