// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: betting.proto

package betting

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BettingServiceClient is the client API for BettingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BettingServiceClient interface {
	CreateSetting(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*SettingsResponse, error)
	UpdateSetting(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*SettingsResponse, error)
	GetSettingsByID(ctx context.Context, in *SettingsById, opts ...grpc.CallOption) (*SettingsResponse, error)
	GetAllSettings(ctx context.Context, in *GetAll, opts ...grpc.CallOption) (*AllSettingsResponse, error)
	CancelBet(ctx context.Context, in *BookingCode, opts ...grpc.CallOption) (*CommonResponseObj, error)
	PlaceBet(ctx context.Context, in *PlaceBetRequest, opts ...grpc.CallOption) (*PlaceBetResponse, error)
	PlaceCasinoBet(ctx context.Context, in *PlaceCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error)
	PlaceVirtualBet(ctx context.Context, in *PlaceVirtualBetRequest, opts ...grpc.CallOption) (*PlaceVirtualBetResponse, error)
	SettleCasinoBet(ctx context.Context, in *SettleCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error)
	CloseCasinoRound(ctx context.Context, in *SettleCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error)
	SettleVirtualBet(ctx context.Context, in *SettleVirtualBetRequest, opts ...grpc.CallOption) (*SettleVirtualBetResponse, error)
	CancelCasinoBet(ctx context.Context, in *RollbackCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error)
	BetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*BetHistoryResponse, error)
	SimulatedBetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*BetHistoryResponse, error)
	FindBet(ctx context.Context, in *FindBetRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	UpdateBet(ctx context.Context, in *UpdateBetRequest, opts ...grpc.CallOption) (*UpdateBetResponse, error)
	GetProbabilityFromBetID(ctx context.Context, in *BetID, opts ...grpc.CallOption) (*Probability, error)
	GetCoupon(ctx context.Context, in *FindBetRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GamingActivity(ctx context.Context, in *GamingActivityRequest, opts ...grpc.CallOption) (*GamingActivityResponse, error)
	GetVirtualBet(ctx context.Context, in *GetVirtualBetRequest, opts ...grpc.CallOption) (*GetVirtualBetResponse, error)
	GetVirtualBets(ctx context.Context, in *GetVirtualBetsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	CashoutRequest(ctx context.Context, in *ProcessCashoutRequest, opts ...grpc.CallOption) (*ProcessCashoutResponse, error)
	GetRetailBets(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetRetailVBets(ctx context.Context, in *GetVirtualBetsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetSalesReport(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetShopUserCommissions(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetTotalSalesReport(ctx context.Context, in *NetworkSalesRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	DeletePlayerData(ctx context.Context, in *SettingsById, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetCommissions(ctx context.Context, in *GetCommissionsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetAgentTotals(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	TicketsReport(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	TaxReport(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetCodeHubTickets(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	PayoutTicket(ctx context.Context, in *BetID, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SaveSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SaveRiskSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SaveUserRiskSettings(ctx context.Context, in *UserRiskSettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	GetGlobalVariables(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetUserRiskSettings(ctx context.Context, in *GetRiskSettingRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	ValidateSelections(ctx context.Context, in *ValidateSelectionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	ManualSettlement(ctx context.Context, in *ManualSettlementRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
}

type bettingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBettingServiceClient(cc grpc.ClientConnInterface) BettingServiceClient {
	return &bettingServiceClient{cc}
}

func (c *bettingServiceClient) CreateSetting(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*SettingsResponse, error) {
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/CreateSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) UpdateSetting(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*SettingsResponse, error) {
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/UpdateSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetSettingsByID(ctx context.Context, in *SettingsById, opts ...grpc.CallOption) (*SettingsResponse, error) {
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetSettingsByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetAllSettings(ctx context.Context, in *GetAll, opts ...grpc.CallOption) (*AllSettingsResponse, error) {
	out := new(AllSettingsResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetAllSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) CancelBet(ctx context.Context, in *BookingCode, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/CancelBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) PlaceBet(ctx context.Context, in *PlaceBetRequest, opts ...grpc.CallOption) (*PlaceBetResponse, error) {
	out := new(PlaceBetResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/PlaceBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) PlaceCasinoBet(ctx context.Context, in *PlaceCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error) {
	out := new(PlaceCasinoBetResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/PlaceCasinoBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) PlaceVirtualBet(ctx context.Context, in *PlaceVirtualBetRequest, opts ...grpc.CallOption) (*PlaceVirtualBetResponse, error) {
	out := new(PlaceVirtualBetResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/PlaceVirtualBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SettleCasinoBet(ctx context.Context, in *SettleCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error) {
	out := new(PlaceCasinoBetResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/SettleCasinoBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) CloseCasinoRound(ctx context.Context, in *SettleCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error) {
	out := new(PlaceCasinoBetResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/CloseCasinoRound", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SettleVirtualBet(ctx context.Context, in *SettleVirtualBetRequest, opts ...grpc.CallOption) (*SettleVirtualBetResponse, error) {
	out := new(SettleVirtualBetResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/SettleVirtualBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) CancelCasinoBet(ctx context.Context, in *RollbackCasinoBetRequest, opts ...grpc.CallOption) (*PlaceCasinoBetResponse, error) {
	out := new(PlaceCasinoBetResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/CancelCasinoBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) BetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*BetHistoryResponse, error) {
	out := new(BetHistoryResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/BetHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SimulatedBetHistory(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*BetHistoryResponse, error) {
	out := new(BetHistoryResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/SimulatedBetHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) FindBet(ctx context.Context, in *FindBetRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/FindBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) UpdateBet(ctx context.Context, in *UpdateBetRequest, opts ...grpc.CallOption) (*UpdateBetResponse, error) {
	out := new(UpdateBetResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/UpdateBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetProbabilityFromBetID(ctx context.Context, in *BetID, opts ...grpc.CallOption) (*Probability, error) {
	out := new(Probability)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetProbabilityFromBetID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetCoupon(ctx context.Context, in *FindBetRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GamingActivity(ctx context.Context, in *GamingActivityRequest, opts ...grpc.CallOption) (*GamingActivityResponse, error) {
	out := new(GamingActivityResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GamingActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetVirtualBet(ctx context.Context, in *GetVirtualBetRequest, opts ...grpc.CallOption) (*GetVirtualBetResponse, error) {
	out := new(GetVirtualBetResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetVirtualBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetVirtualBets(ctx context.Context, in *GetVirtualBetsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetVirtualBets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) CashoutRequest(ctx context.Context, in *ProcessCashoutRequest, opts ...grpc.CallOption) (*ProcessCashoutResponse, error) {
	out := new(ProcessCashoutResponse)
	err := c.cc.Invoke(ctx, "/betting.BettingService/CashoutRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetRetailBets(ctx context.Context, in *BetHistoryRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetRetailBets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetRetailVBets(ctx context.Context, in *GetVirtualBetsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetRetailVBets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetSalesReport(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetSalesReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetShopUserCommissions(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetShopUserCommissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetTotalSalesReport(ctx context.Context, in *NetworkSalesRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetTotalSalesReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) DeletePlayerData(ctx context.Context, in *SettingsById, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/DeletePlayerData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetCommissions(ctx context.Context, in *GetCommissionsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetCommissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetAgentTotals(ctx context.Context, in *SalesReportRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetAgentTotals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) TicketsReport(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/TicketsReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) TaxReport(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/TaxReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetCodeHubTickets(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetCodeHubTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) PayoutTicket(ctx context.Context, in *BetID, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/PayoutTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SaveSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/SaveSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SaveRiskSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/SaveRiskSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SaveUserRiskSettings(ctx context.Context, in *UserRiskSettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/SaveUserRiskSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetGlobalVariables(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetGlobalVariables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetUserRiskSettings(ctx context.Context, in *GetRiskSettingRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/GetUserRiskSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) ValidateSelections(ctx context.Context, in *ValidateSelectionRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/ValidateSelections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) ManualSettlement(ctx context.Context, in *ManualSettlementRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/betting.BettingService/ManualSettlement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BettingServiceServer is the server API for BettingService service.
// All implementations must embed UnimplementedBettingServiceServer
// for forward compatibility
type BettingServiceServer interface {
	CreateSetting(context.Context, *Settings) (*SettingsResponse, error)
	UpdateSetting(context.Context, *Settings) (*SettingsResponse, error)
	GetSettingsByID(context.Context, *SettingsById) (*SettingsResponse, error)
	GetAllSettings(context.Context, *GetAll) (*AllSettingsResponse, error)
	CancelBet(context.Context, *BookingCode) (*CommonResponseObj, error)
	PlaceBet(context.Context, *PlaceBetRequest) (*PlaceBetResponse, error)
	PlaceCasinoBet(context.Context, *PlaceCasinoBetRequest) (*PlaceCasinoBetResponse, error)
	PlaceVirtualBet(context.Context, *PlaceVirtualBetRequest) (*PlaceVirtualBetResponse, error)
	SettleCasinoBet(context.Context, *SettleCasinoBetRequest) (*PlaceCasinoBetResponse, error)
	CloseCasinoRound(context.Context, *SettleCasinoBetRequest) (*PlaceCasinoBetResponse, error)
	SettleVirtualBet(context.Context, *SettleVirtualBetRequest) (*SettleVirtualBetResponse, error)
	CancelCasinoBet(context.Context, *RollbackCasinoBetRequest) (*PlaceCasinoBetResponse, error)
	BetHistory(context.Context, *BetHistoryRequest) (*BetHistoryResponse, error)
	SimulatedBetHistory(context.Context, *BetHistoryRequest) (*BetHistoryResponse, error)
	FindBet(context.Context, *FindBetRequest) (*CommonResponseObj, error)
	UpdateBet(context.Context, *UpdateBetRequest) (*UpdateBetResponse, error)
	GetProbabilityFromBetID(context.Context, *BetID) (*Probability, error)
	GetCoupon(context.Context, *FindBetRequest) (*CommonResponseObj, error)
	GamingActivity(context.Context, *GamingActivityRequest) (*GamingActivityResponse, error)
	GetVirtualBet(context.Context, *GetVirtualBetRequest) (*GetVirtualBetResponse, error)
	GetVirtualBets(context.Context, *GetVirtualBetsRequest) (*CommonResponseObj, error)
	CashoutRequest(context.Context, *ProcessCashoutRequest) (*ProcessCashoutResponse, error)
	GetRetailBets(context.Context, *BetHistoryRequest) (*CommonResponseObj, error)
	GetRetailVBets(context.Context, *GetVirtualBetsRequest) (*CommonResponseObj, error)
	GetSalesReport(context.Context, *SalesReportRequest) (*CommonResponseObj, error)
	GetShopUserCommissions(context.Context, *SalesReportRequest) (*CommonResponseObj, error)
	GetTotalSalesReport(context.Context, *NetworkSalesRequest) (*CommonResponseObj, error)
	DeletePlayerData(context.Context, *SettingsById) (*CommonResponseObj, error)
	GetCommissions(context.Context, *GetCommissionsRequest) (*CommonResponseObj, error)
	GetAgentTotals(context.Context, *SalesReportRequest) (*CommonResponseArray, error)
	TicketsReport(context.Context, *GetTicketsRequest) (*CommonResponseObj, error)
	TaxReport(context.Context, *GetTicketsRequest) (*CommonResponseObj, error)
	GetCodeHubTickets(context.Context, *GetTicketsRequest) (*CommonResponseObj, error)
	PayoutTicket(context.Context, *BetID) (*CommonResponseObj, error)
	SaveSettings(context.Context, *SettingsRequest) (*CommonResponseObj, error)
	SaveRiskSettings(context.Context, *SettingsRequest) (*CommonResponseObj, error)
	SaveUserRiskSettings(context.Context, *UserRiskSettingsRequest) (*CommonResponseObj, error)
	GetSettings(context.Context, *GetSettingsRequest) (*CommonResponseArray, error)
	GetGlobalVariables(context.Context, *GetSettingsRequest) (*CommonResponseObj, error)
	GetUserRiskSettings(context.Context, *GetRiskSettingRequest) (*CommonResponseObj, error)
	ValidateSelections(context.Context, *ValidateSelectionRequest) (*CommonResponseObj, error)
	ManualSettlement(context.Context, *ManualSettlementRequest) (*CommonResponseObj, error)
	mustEmbedUnimplementedBettingServiceServer()
}

// UnimplementedBettingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBettingServiceServer struct {
}

func (UnimplementedBettingServiceServer) CreateSetting(context.Context, *Settings) (*SettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSetting not implemented")
}
func (UnimplementedBettingServiceServer) UpdateSetting(context.Context, *Settings) (*SettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSetting not implemented")
}
func (UnimplementedBettingServiceServer) GetSettingsByID(context.Context, *SettingsById) (*SettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettingsByID not implemented")
}
func (UnimplementedBettingServiceServer) GetAllSettings(context.Context, *GetAll) (*AllSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllSettings not implemented")
}
func (UnimplementedBettingServiceServer) CancelBet(context.Context, *BookingCode) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBet not implemented")
}
func (UnimplementedBettingServiceServer) PlaceBet(context.Context, *PlaceBetRequest) (*PlaceBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceBet not implemented")
}
func (UnimplementedBettingServiceServer) PlaceCasinoBet(context.Context, *PlaceCasinoBetRequest) (*PlaceCasinoBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceCasinoBet not implemented")
}
func (UnimplementedBettingServiceServer) PlaceVirtualBet(context.Context, *PlaceVirtualBetRequest) (*PlaceVirtualBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceVirtualBet not implemented")
}
func (UnimplementedBettingServiceServer) SettleCasinoBet(context.Context, *SettleCasinoBetRequest) (*PlaceCasinoBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleCasinoBet not implemented")
}
func (UnimplementedBettingServiceServer) CloseCasinoRound(context.Context, *SettleCasinoBetRequest) (*PlaceCasinoBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseCasinoRound not implemented")
}
func (UnimplementedBettingServiceServer) SettleVirtualBet(context.Context, *SettleVirtualBetRequest) (*SettleVirtualBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleVirtualBet not implemented")
}
func (UnimplementedBettingServiceServer) CancelCasinoBet(context.Context, *RollbackCasinoBetRequest) (*PlaceCasinoBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCasinoBet not implemented")
}
func (UnimplementedBettingServiceServer) BetHistory(context.Context, *BetHistoryRequest) (*BetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BetHistory not implemented")
}
func (UnimplementedBettingServiceServer) SimulatedBetHistory(context.Context, *BetHistoryRequest) (*BetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimulatedBetHistory not implemented")
}
func (UnimplementedBettingServiceServer) FindBet(context.Context, *FindBetRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBet not implemented")
}
func (UnimplementedBettingServiceServer) UpdateBet(context.Context, *UpdateBetRequest) (*UpdateBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBet not implemented")
}
func (UnimplementedBettingServiceServer) GetProbabilityFromBetID(context.Context, *BetID) (*Probability, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProbabilityFromBetID not implemented")
}
func (UnimplementedBettingServiceServer) GetCoupon(context.Context, *FindBetRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoupon not implemented")
}
func (UnimplementedBettingServiceServer) GamingActivity(context.Context, *GamingActivityRequest) (*GamingActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GamingActivity not implemented")
}
func (UnimplementedBettingServiceServer) GetVirtualBet(context.Context, *GetVirtualBetRequest) (*GetVirtualBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVirtualBet not implemented")
}
func (UnimplementedBettingServiceServer) GetVirtualBets(context.Context, *GetVirtualBetsRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVirtualBets not implemented")
}
func (UnimplementedBettingServiceServer) CashoutRequest(context.Context, *ProcessCashoutRequest) (*ProcessCashoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CashoutRequest not implemented")
}
func (UnimplementedBettingServiceServer) GetRetailBets(context.Context, *BetHistoryRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRetailBets not implemented")
}
func (UnimplementedBettingServiceServer) GetRetailVBets(context.Context, *GetVirtualBetsRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRetailVBets not implemented")
}
func (UnimplementedBettingServiceServer) GetSalesReport(context.Context, *SalesReportRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSalesReport not implemented")
}
func (UnimplementedBettingServiceServer) GetShopUserCommissions(context.Context, *SalesReportRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopUserCommissions not implemented")
}
func (UnimplementedBettingServiceServer) GetTotalSalesReport(context.Context, *NetworkSalesRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalSalesReport not implemented")
}
func (UnimplementedBettingServiceServer) DeletePlayerData(context.Context, *SettingsById) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlayerData not implemented")
}
func (UnimplementedBettingServiceServer) GetCommissions(context.Context, *GetCommissionsRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommissions not implemented")
}
func (UnimplementedBettingServiceServer) GetAgentTotals(context.Context, *SalesReportRequest) (*CommonResponseArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentTotals not implemented")
}
func (UnimplementedBettingServiceServer) TicketsReport(context.Context, *GetTicketsRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TicketsReport not implemented")
}
func (UnimplementedBettingServiceServer) TaxReport(context.Context, *GetTicketsRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaxReport not implemented")
}
func (UnimplementedBettingServiceServer) GetCodeHubTickets(context.Context, *GetTicketsRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCodeHubTickets not implemented")
}
func (UnimplementedBettingServiceServer) PayoutTicket(context.Context, *BetID) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayoutTicket not implemented")
}
func (UnimplementedBettingServiceServer) SaveSettings(context.Context, *SettingsRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveSettings not implemented")
}
func (UnimplementedBettingServiceServer) SaveRiskSettings(context.Context, *SettingsRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRiskSettings not implemented")
}
func (UnimplementedBettingServiceServer) SaveUserRiskSettings(context.Context, *UserRiskSettingsRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveUserRiskSettings not implemented")
}
func (UnimplementedBettingServiceServer) GetSettings(context.Context, *GetSettingsRequest) (*CommonResponseArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedBettingServiceServer) GetGlobalVariables(context.Context, *GetSettingsRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalVariables not implemented")
}
func (UnimplementedBettingServiceServer) GetUserRiskSettings(context.Context, *GetRiskSettingRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRiskSettings not implemented")
}
func (UnimplementedBettingServiceServer) ValidateSelections(context.Context, *ValidateSelectionRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSelections not implemented")
}
func (UnimplementedBettingServiceServer) ManualSettlement(context.Context, *ManualSettlementRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManualSettlement not implemented")
}
func (UnimplementedBettingServiceServer) mustEmbedUnimplementedBettingServiceServer() {}

// UnsafeBettingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BettingServiceServer will
// result in compilation errors.
type UnsafeBettingServiceServer interface {
	mustEmbedUnimplementedBettingServiceServer()
}

func RegisterBettingServiceServer(s grpc.ServiceRegistrar, srv BettingServiceServer) {
	s.RegisterService(&BettingService_ServiceDesc, srv)
}

func _BettingService_CreateSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Settings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CreateSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/CreateSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CreateSetting(ctx, req.(*Settings))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_UpdateSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Settings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).UpdateSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/UpdateSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).UpdateSetting(ctx, req.(*Settings))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetSettingsByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetSettingsByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetSettingsByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetSettingsByID(ctx, req.(*SettingsById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetAllSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAll)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetAllSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetAllSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetAllSettings(ctx, req.(*GetAll))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_CancelBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CancelBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/CancelBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CancelBet(ctx, req.(*BookingCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_PlaceBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).PlaceBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/PlaceBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).PlaceBet(ctx, req.(*PlaceBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_PlaceCasinoBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceCasinoBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).PlaceCasinoBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/PlaceCasinoBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).PlaceCasinoBet(ctx, req.(*PlaceCasinoBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_PlaceVirtualBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceVirtualBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).PlaceVirtualBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/PlaceVirtualBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).PlaceVirtualBet(ctx, req.(*PlaceVirtualBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SettleCasinoBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleCasinoBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SettleCasinoBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/SettleCasinoBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SettleCasinoBet(ctx, req.(*SettleCasinoBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_CloseCasinoRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleCasinoBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CloseCasinoRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/CloseCasinoRound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CloseCasinoRound(ctx, req.(*SettleCasinoBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SettleVirtualBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleVirtualBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SettleVirtualBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/SettleVirtualBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SettleVirtualBet(ctx, req.(*SettleVirtualBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_CancelCasinoBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackCasinoBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CancelCasinoBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/CancelCasinoBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CancelCasinoBet(ctx, req.(*RollbackCasinoBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_BetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).BetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/BetHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).BetHistory(ctx, req.(*BetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SimulatedBetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SimulatedBetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/SimulatedBetHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SimulatedBetHistory(ctx, req.(*BetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_FindBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).FindBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/FindBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).FindBet(ctx, req.(*FindBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_UpdateBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).UpdateBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/UpdateBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).UpdateBet(ctx, req.(*UpdateBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetProbabilityFromBetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetProbabilityFromBetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetProbabilityFromBetID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetProbabilityFromBetID(ctx, req.(*BetID))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetCoupon(ctx, req.(*FindBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GamingActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GamingActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GamingActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GamingActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GamingActivity(ctx, req.(*GamingActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetVirtualBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirtualBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetVirtualBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetVirtualBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetVirtualBet(ctx, req.(*GetVirtualBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetVirtualBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirtualBetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetVirtualBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetVirtualBets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetVirtualBets(ctx, req.(*GetVirtualBetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_CashoutRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessCashoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CashoutRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/CashoutRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CashoutRequest(ctx, req.(*ProcessCashoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetRetailBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetRetailBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetRetailBets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetRetailBets(ctx, req.(*BetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetRetailVBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirtualBetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetRetailVBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetRetailVBets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetRetailVBets(ctx, req.(*GetVirtualBetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetSalesReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetSalesReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetSalesReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetSalesReport(ctx, req.(*SalesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetShopUserCommissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetShopUserCommissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetShopUserCommissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetShopUserCommissions(ctx, req.(*SalesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetTotalSalesReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkSalesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetTotalSalesReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetTotalSalesReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetTotalSalesReport(ctx, req.(*NetworkSalesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_DeletePlayerData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).DeletePlayerData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/DeletePlayerData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).DeletePlayerData(ctx, req.(*SettingsById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetCommissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetCommissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetCommissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetCommissions(ctx, req.(*GetCommissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetAgentTotals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetAgentTotals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetAgentTotals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetAgentTotals(ctx, req.(*SalesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_TicketsReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).TicketsReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/TicketsReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).TicketsReport(ctx, req.(*GetTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_TaxReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).TaxReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/TaxReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).TaxReport(ctx, req.(*GetTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetCodeHubTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetCodeHubTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetCodeHubTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetCodeHubTickets(ctx, req.(*GetTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_PayoutTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).PayoutTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/PayoutTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).PayoutTicket(ctx, req.(*BetID))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SaveSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SaveSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/SaveSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SaveSettings(ctx, req.(*SettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SaveRiskSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SaveRiskSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/SaveRiskSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SaveRiskSettings(ctx, req.(*SettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SaveUserRiskSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRiskSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SaveUserRiskSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/SaveUserRiskSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SaveUserRiskSettings(ctx, req.(*UserRiskSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetGlobalVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetGlobalVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetGlobalVariables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetGlobalVariables(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetUserRiskSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiskSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetUserRiskSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/GetUserRiskSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetUserRiskSettings(ctx, req.(*GetRiskSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_ValidateSelections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).ValidateSelections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/ValidateSelections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).ValidateSelections(ctx, req.(*ValidateSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_ManualSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManualSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).ManualSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betting.BettingService/ManualSettlement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).ManualSettlement(ctx, req.(*ManualSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BettingService_ServiceDesc is the grpc.ServiceDesc for BettingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BettingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "betting.BettingService",
	HandlerType: (*BettingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSetting",
			Handler:    _BettingService_CreateSetting_Handler,
		},
		{
			MethodName: "UpdateSetting",
			Handler:    _BettingService_UpdateSetting_Handler,
		},
		{
			MethodName: "GetSettingsByID",
			Handler:    _BettingService_GetSettingsByID_Handler,
		},
		{
			MethodName: "GetAllSettings",
			Handler:    _BettingService_GetAllSettings_Handler,
		},
		{
			MethodName: "CancelBet",
			Handler:    _BettingService_CancelBet_Handler,
		},
		{
			MethodName: "PlaceBet",
			Handler:    _BettingService_PlaceBet_Handler,
		},
		{
			MethodName: "PlaceCasinoBet",
			Handler:    _BettingService_PlaceCasinoBet_Handler,
		},
		{
			MethodName: "PlaceVirtualBet",
			Handler:    _BettingService_PlaceVirtualBet_Handler,
		},
		{
			MethodName: "SettleCasinoBet",
			Handler:    _BettingService_SettleCasinoBet_Handler,
		},
		{
			MethodName: "CloseCasinoRound",
			Handler:    _BettingService_CloseCasinoRound_Handler,
		},
		{
			MethodName: "SettleVirtualBet",
			Handler:    _BettingService_SettleVirtualBet_Handler,
		},
		{
			MethodName: "CancelCasinoBet",
			Handler:    _BettingService_CancelCasinoBet_Handler,
		},
		{
			MethodName: "BetHistory",
			Handler:    _BettingService_BetHistory_Handler,
		},
		{
			MethodName: "SimulatedBetHistory",
			Handler:    _BettingService_SimulatedBetHistory_Handler,
		},
		{
			MethodName: "FindBet",
			Handler:    _BettingService_FindBet_Handler,
		},
		{
			MethodName: "UpdateBet",
			Handler:    _BettingService_UpdateBet_Handler,
		},
		{
			MethodName: "GetProbabilityFromBetID",
			Handler:    _BettingService_GetProbabilityFromBetID_Handler,
		},
		{
			MethodName: "GetCoupon",
			Handler:    _BettingService_GetCoupon_Handler,
		},
		{
			MethodName: "GamingActivity",
			Handler:    _BettingService_GamingActivity_Handler,
		},
		{
			MethodName: "GetVirtualBet",
			Handler:    _BettingService_GetVirtualBet_Handler,
		},
		{
			MethodName: "GetVirtualBets",
			Handler:    _BettingService_GetVirtualBets_Handler,
		},
		{
			MethodName: "CashoutRequest",
			Handler:    _BettingService_CashoutRequest_Handler,
		},
		{
			MethodName: "GetRetailBets",
			Handler:    _BettingService_GetRetailBets_Handler,
		},
		{
			MethodName: "GetRetailVBets",
			Handler:    _BettingService_GetRetailVBets_Handler,
		},
		{
			MethodName: "GetSalesReport",
			Handler:    _BettingService_GetSalesReport_Handler,
		},
		{
			MethodName: "GetShopUserCommissions",
			Handler:    _BettingService_GetShopUserCommissions_Handler,
		},
		{
			MethodName: "GetTotalSalesReport",
			Handler:    _BettingService_GetTotalSalesReport_Handler,
		},
		{
			MethodName: "DeletePlayerData",
			Handler:    _BettingService_DeletePlayerData_Handler,
		},
		{
			MethodName: "GetCommissions",
			Handler:    _BettingService_GetCommissions_Handler,
		},
		{
			MethodName: "GetAgentTotals",
			Handler:    _BettingService_GetAgentTotals_Handler,
		},
		{
			MethodName: "TicketsReport",
			Handler:    _BettingService_TicketsReport_Handler,
		},
		{
			MethodName: "TaxReport",
			Handler:    _BettingService_TaxReport_Handler,
		},
		{
			MethodName: "GetCodeHubTickets",
			Handler:    _BettingService_GetCodeHubTickets_Handler,
		},
		{
			MethodName: "PayoutTicket",
			Handler:    _BettingService_PayoutTicket_Handler,
		},
		{
			MethodName: "SaveSettings",
			Handler:    _BettingService_SaveSettings_Handler,
		},
		{
			MethodName: "SaveRiskSettings",
			Handler:    _BettingService_SaveRiskSettings_Handler,
		},
		{
			MethodName: "SaveUserRiskSettings",
			Handler:    _BettingService_SaveUserRiskSettings_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _BettingService_GetSettings_Handler,
		},
		{
			MethodName: "GetGlobalVariables",
			Handler:    _BettingService_GetGlobalVariables_Handler,
		},
		{
			MethodName: "GetUserRiskSettings",
			Handler:    _BettingService_GetUserRiskSettings_Handler,
		},
		{
			MethodName: "ValidateSelections",
			Handler:    _BettingService_ValidateSelections_Handler,
		},
		{
			MethodName: "ManualSettlement",
			Handler:    _BettingService_ManualSettlement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "betting.proto",
}
