// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: affiliate.proto

package affiliate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAffiliateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CompanyName    string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	ContactEmail   string                 `protobuf:"bytes,3,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	CommissionRate float64                `protobuf:"fixed64,4,opt,name=commission_rate,json=commissionRate,proto3" json:"commission_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAffiliateRequest) Reset() {
	*x = CreateAffiliateRequest{}
	mi := &file_affiliate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAffiliateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAffiliateRequest) ProtoMessage() {}

func (x *CreateAffiliateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_affiliate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAffiliateRequest.ProtoReflect.Descriptor instead.
func (*CreateAffiliateRequest) Descriptor() ([]byte, []int) {
	return file_affiliate_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAffiliateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateAffiliateRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *CreateAffiliateRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *CreateAffiliateRequest) GetCommissionRate() float64 {
	if x != nil {
		return x.CommissionRate
	}
	return 0
}

type CommonResponseArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *int32                 `protobuf:"varint,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Success       *bool                  `protobuf:"varint,2,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*structpb.Struct     `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	Errors        *string                `protobuf:"bytes,5,opt,name=errors,proto3,oneof" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponseArray) Reset() {
	*x = CommonResponseArray{}
	mi := &file_affiliate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponseArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponseArray) ProtoMessage() {}

func (x *CommonResponseArray) ProtoReflect() protoreflect.Message {
	mi := &file_affiliate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponseArray.ProtoReflect.Descriptor instead.
func (*CommonResponseArray) Descriptor() ([]byte, []int) {
	return file_affiliate_proto_rawDescGZIP(), []int{1}
}

func (x *CommonResponseArray) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *CommonResponseArray) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *CommonResponseArray) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonResponseArray) GetData() []*structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommonResponseArray) GetErrors() string {
	if x != nil && x.Errors != nil {
		return *x.Errors
	}
	return ""
}

type CommonResponseObj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *int32                 `protobuf:"varint,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Success       *bool                  `protobuf:"varint,2,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Errors        *string                `protobuf:"bytes,5,opt,name=errors,proto3,oneof" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponseObj) Reset() {
	*x = CommonResponseObj{}
	mi := &file_affiliate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponseObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponseObj) ProtoMessage() {}

func (x *CommonResponseObj) ProtoReflect() protoreflect.Message {
	mi := &file_affiliate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponseObj.ProtoReflect.Descriptor instead.
func (*CommonResponseObj) Descriptor() ([]byte, []int) {
	return file_affiliate_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResponseObj) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *CommonResponseObj) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *CommonResponseObj) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonResponseObj) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommonResponseObj) GetErrors() string {
	if x != nil && x.Errors != nil {
		return *x.Errors
	}
	return ""
}

var File_affiliate_proto protoreflect.FileDescriptor

const file_affiliate_proto_rawDesc = "" +
	"\n" +
	"\x0faffiliate.proto\x12\taffiliate\x1a\x1cgoogle/protobuf/struct.proto\"\xa6\x01\n" +
	"\x16CreateAffiliateRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12#\n" +
	"\rcontact_email\x18\x03 \x01(\tR\fcontactEmail\x12'\n" +
	"\x0fcommission_rate\x18\x04 \x01(\x01R\x0ecommissionRate\"\xd7\x01\n" +
	"\x13CommonResponseArray\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\x05H\x00R\x06status\x88\x01\x01\x12\x1d\n" +
	"\asuccess\x18\x02 \x01(\bH\x01R\asuccess\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x04 \x03(\v2\x17.google.protobuf.StructR\x04data\x12\x1b\n" +
	"\x06errors\x18\x05 \x01(\tH\x02R\x06errors\x88\x01\x01B\t\n" +
	"\a_statusB\n" +
	"\n" +
	"\b_successB\t\n" +
	"\a_errors\"\xe3\x01\n" +
	"\x11CommonResponseObj\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\x05H\x00R\x06status\x88\x01\x01\x12\x1d\n" +
	"\asuccess\x18\x02 \x01(\bH\x01R\asuccess\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x02R\x04data\x88\x01\x01\x12\x1b\n" +
	"\x06errors\x18\x05 \x01(\tH\x03R\x06errors\x88\x01\x01B\t\n" +
	"\a_statusB\n" +
	"\n" +
	"\b_successB\a\n" +
	"\x05_dataB\t\n" +
	"\a_errors2f\n" +
	"\x10AffiliateService\x12R\n" +
	"\x0fCreateAffiliate\x12!.affiliate.CreateAffiliateRequest\x1a\x1c.affiliate.CommonResponseObjB Z\x1ewallet-service/proto/affiliateb\x06proto3"

var (
	file_affiliate_proto_rawDescOnce sync.Once
	file_affiliate_proto_rawDescData []byte
)

func file_affiliate_proto_rawDescGZIP() []byte {
	file_affiliate_proto_rawDescOnce.Do(func() {
		file_affiliate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_affiliate_proto_rawDesc), len(file_affiliate_proto_rawDesc)))
	})
	return file_affiliate_proto_rawDescData
}

var file_affiliate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_affiliate_proto_goTypes = []any{
	(*CreateAffiliateRequest)(nil), // 0: affiliate.CreateAffiliateRequest
	(*CommonResponseArray)(nil),    // 1: affiliate.CommonResponseArray
	(*CommonResponseObj)(nil),      // 2: affiliate.CommonResponseObj
	(*structpb.Struct)(nil),        // 3: google.protobuf.Struct
}
var file_affiliate_proto_depIdxs = []int32{
	3, // 0: affiliate.CommonResponseArray.data:type_name -> google.protobuf.Struct
	3, // 1: affiliate.CommonResponseObj.data:type_name -> google.protobuf.Struct
	0, // 2: affiliate.AffiliateService.CreateAffiliate:input_type -> affiliate.CreateAffiliateRequest
	2, // 3: affiliate.AffiliateService.CreateAffiliate:output_type -> affiliate.CommonResponseObj
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_affiliate_proto_init() }
func file_affiliate_proto_init() {
	if File_affiliate_proto != nil {
		return
	}
	file_affiliate_proto_msgTypes[1].OneofWrappers = []any{}
	file_affiliate_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_affiliate_proto_rawDesc), len(file_affiliate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_affiliate_proto_goTypes,
		DependencyIndexes: file_affiliate_proto_depIdxs,
		MessageInfos:      file_affiliate_proto_msgTypes,
	}.Build()
	File_affiliate_proto = out.File
	file_affiliate_proto_goTypes = nil
	file_affiliate_proto_depIdxs = nil
}
