// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: bonus.proto

package bonus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BonusServiceClient is the client API for BonusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BonusServiceClient interface {
	FetchBonusReport(ctx context.Context, in *FetchReportRequest, opts ...grpc.CallOption) (*FetchReportResponse, error)
	CreateBonus(ctx context.Context, in *CreateBonusRequest, opts ...grpc.CallOption) (*CreateBonusResponse, error)
	UpdateBonus(ctx context.Context, in *CreateBonusRequest, opts ...grpc.CallOption) (*CreateBonusResponse, error)
	GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*GetCampaignResponse, error)
	ValidateBetSelections(ctx context.Context, in *UserBet, opts ...grpc.CallOption) (*ValidateBetResponse, error)
	CheckDepositBonus(ctx context.Context, in *CheckDepositBonusRequest, opts ...grpc.CallOption) (*CheckDepositBonusResponse, error)
	CheckRegisterBonus(ctx context.Context, in *GetBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	CheckAffiliateRegisterBonus(ctx context.Context, in *GetBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SettleBet(ctx context.Context, in *SettleBetRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SearchBonus(ctx context.Context, in *GetBonusByClientID, opts ...grpc.CallOption) (*SearchBonusResponse, error)
	GetActiveUserBonus(ctx context.Context, in *CheckDepositBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	SaveAccaBonus(ctx context.Context, in *SaveAccaBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetAccaBonuses(ctx context.Context, in *GetAllBonusRequest, opts ...grpc.CallOption) (*CommonResponseArray, error)
	GetBonus(ctx context.Context, in *GetBonusRequest, opts ...grpc.CallOption) (*GetBonusResponse, error)
	GetAffiliateBonus(ctx context.Context, in *GetAffiliateBonusRequest, opts ...grpc.CallOption) (*GetBonusResponse, error)
	GetAffiliateWithBonus(ctx context.Context, in *AffiliateBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	CheckCashBackBonus(ctx context.Context, in *GetBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetAllAwardedBonus(ctx context.Context, in *GetAllBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	GetBonusWithPromoCode(ctx context.Context, in *GetBonusWithPromoCodeRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	DeleteBonus(ctx context.Context, in *DeleteBonusRequest, opts ...grpc.CallOption) (*BonusResponse, error)
	GetUserBonus(ctx context.Context, in *GetUserBonusRequest, opts ...grpc.CallOption) (*GetUserBonusResponse, error)
	AwardBonus(ctx context.Context, in *AwardBonusRequest, opts ...grpc.CallOption) (*UserBonusResponse, error)
	AssignAffiliateBonus(ctx context.Context, in *AssignBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	DeactivateUserBonus(ctx context.Context, in *BonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error)
	PlaceBonusBet(ctx context.Context, in *UserBet, opts ...grpc.CallOption) (*PlaceBetResponse, error)
	UpdateBonusStatus(ctx context.Context, in *BonusStatusRequest, opts ...grpc.CallOption) (*CreateBonusResponse, error)
	CreateCampaignBonus(ctx context.Context, in *CreateCampaignBonusDto, opts ...grpc.CallOption) (*CreateBonusResponse, error)
	UpdateCampaignBonus(ctx context.Context, in *UpdateCampaignBonusDto, opts ...grpc.CallOption) (*CreateBonusResponse, error)
	DeleteCampaignBonus(ctx context.Context, in *DeleteBonusRequest, opts ...grpc.CallOption) (*CreateBonusResponse, error)
	RedeemCampaignBonus(ctx context.Context, in *RedeemCampaignBonusDto, opts ...grpc.CallOption) (*CreateBonusResponse, error)
	GetCampaignBonus(ctx context.Context, in *GetBonusByClientID, opts ...grpc.CallOption) (*AllCampaignBonus, error)
	DeletePlayerData(ctx context.Context, in *GetBonusRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type bonusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBonusServiceClient(cc grpc.ClientConnInterface) BonusServiceClient {
	return &bonusServiceClient{cc}
}

func (c *bonusServiceClient) FetchBonusReport(ctx context.Context, in *FetchReportRequest, opts ...grpc.CallOption) (*FetchReportResponse, error) {
	out := new(FetchReportResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/fetchBonusReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) CreateBonus(ctx context.Context, in *CreateBonusRequest, opts ...grpc.CallOption) (*CreateBonusResponse, error) {
	out := new(CreateBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/CreateBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) UpdateBonus(ctx context.Context, in *CreateBonusRequest, opts ...grpc.CallOption) (*CreateBonusResponse, error) {
	out := new(CreateBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/UpdateBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*GetCampaignResponse, error) {
	out := new(GetCampaignResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/GetCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) ValidateBetSelections(ctx context.Context, in *UserBet, opts ...grpc.CallOption) (*ValidateBetResponse, error) {
	out := new(ValidateBetResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/ValidateBetSelections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) CheckDepositBonus(ctx context.Context, in *CheckDepositBonusRequest, opts ...grpc.CallOption) (*CheckDepositBonusResponse, error) {
	out := new(CheckDepositBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/CheckDepositBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) CheckRegisterBonus(ctx context.Context, in *GetBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/CheckRegisterBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) CheckAffiliateRegisterBonus(ctx context.Context, in *GetBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/CheckAffiliateRegisterBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) SettleBet(ctx context.Context, in *SettleBetRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/SettleBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) SearchBonus(ctx context.Context, in *GetBonusByClientID, opts ...grpc.CallOption) (*SearchBonusResponse, error) {
	out := new(SearchBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/SearchBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) GetActiveUserBonus(ctx context.Context, in *CheckDepositBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/GetActiveUserBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) SaveAccaBonus(ctx context.Context, in *SaveAccaBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/SaveAccaBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) GetAccaBonuses(ctx context.Context, in *GetAllBonusRequest, opts ...grpc.CallOption) (*CommonResponseArray, error) {
	out := new(CommonResponseArray)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/GetAccaBonuses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) GetBonus(ctx context.Context, in *GetBonusRequest, opts ...grpc.CallOption) (*GetBonusResponse, error) {
	out := new(GetBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/GetBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) GetAffiliateBonus(ctx context.Context, in *GetAffiliateBonusRequest, opts ...grpc.CallOption) (*GetBonusResponse, error) {
	out := new(GetBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/GetAffiliateBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) GetAffiliateWithBonus(ctx context.Context, in *AffiliateBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/GetAffiliateWithBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) CheckCashBackBonus(ctx context.Context, in *GetBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/CheckCashBackBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) GetAllAwardedBonus(ctx context.Context, in *GetAllBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/GetAllAwardedBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) GetBonusWithPromoCode(ctx context.Context, in *GetBonusWithPromoCodeRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/GetBonusWithPromoCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) DeleteBonus(ctx context.Context, in *DeleteBonusRequest, opts ...grpc.CallOption) (*BonusResponse, error) {
	out := new(BonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/DeleteBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) GetUserBonus(ctx context.Context, in *GetUserBonusRequest, opts ...grpc.CallOption) (*GetUserBonusResponse, error) {
	out := new(GetUserBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/GetUserBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) AwardBonus(ctx context.Context, in *AwardBonusRequest, opts ...grpc.CallOption) (*UserBonusResponse, error) {
	out := new(UserBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/AwardBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) AssignAffiliateBonus(ctx context.Context, in *AssignBonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/AssignAffiliateBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) DeactivateUserBonus(ctx context.Context, in *BonusRequest, opts ...grpc.CallOption) (*CommonResponseObj, error) {
	out := new(CommonResponseObj)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/DeactivateUserBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) PlaceBonusBet(ctx context.Context, in *UserBet, opts ...grpc.CallOption) (*PlaceBetResponse, error) {
	out := new(PlaceBetResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/PlaceBonusBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) UpdateBonusStatus(ctx context.Context, in *BonusStatusRequest, opts ...grpc.CallOption) (*CreateBonusResponse, error) {
	out := new(CreateBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/UpdateBonusStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) CreateCampaignBonus(ctx context.Context, in *CreateCampaignBonusDto, opts ...grpc.CallOption) (*CreateBonusResponse, error) {
	out := new(CreateBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/CreateCampaignBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) UpdateCampaignBonus(ctx context.Context, in *UpdateCampaignBonusDto, opts ...grpc.CallOption) (*CreateBonusResponse, error) {
	out := new(CreateBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/UpdateCampaignBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) DeleteCampaignBonus(ctx context.Context, in *DeleteBonusRequest, opts ...grpc.CallOption) (*CreateBonusResponse, error) {
	out := new(CreateBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/DeleteCampaignBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) RedeemCampaignBonus(ctx context.Context, in *RedeemCampaignBonusDto, opts ...grpc.CallOption) (*CreateBonusResponse, error) {
	out := new(CreateBonusResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/RedeemCampaignBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) GetCampaignBonus(ctx context.Context, in *GetBonusByClientID, opts ...grpc.CallOption) (*AllCampaignBonus, error) {
	out := new(AllCampaignBonus)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/GetCampaignBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) DeletePlayerData(ctx context.Context, in *GetBonusRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/bonus.BonusService/DeletePlayerData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BonusServiceServer is the server API for BonusService service.
// All implementations must embed UnimplementedBonusServiceServer
// for forward compatibility
type BonusServiceServer interface {
	FetchBonusReport(context.Context, *FetchReportRequest) (*FetchReportResponse, error)
	CreateBonus(context.Context, *CreateBonusRequest) (*CreateBonusResponse, error)
	UpdateBonus(context.Context, *CreateBonusRequest) (*CreateBonusResponse, error)
	GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignResponse, error)
	ValidateBetSelections(context.Context, *UserBet) (*ValidateBetResponse, error)
	CheckDepositBonus(context.Context, *CheckDepositBonusRequest) (*CheckDepositBonusResponse, error)
	CheckRegisterBonus(context.Context, *GetBonusRequest) (*CommonResponseObj, error)
	CheckAffiliateRegisterBonus(context.Context, *GetBonusRequest) (*CommonResponseObj, error)
	SettleBet(context.Context, *SettleBetRequest) (*CommonResponseObj, error)
	SearchBonus(context.Context, *GetBonusByClientID) (*SearchBonusResponse, error)
	GetActiveUserBonus(context.Context, *CheckDepositBonusRequest) (*CommonResponseObj, error)
	SaveAccaBonus(context.Context, *SaveAccaBonusRequest) (*CommonResponseObj, error)
	GetAccaBonuses(context.Context, *GetAllBonusRequest) (*CommonResponseArray, error)
	GetBonus(context.Context, *GetBonusRequest) (*GetBonusResponse, error)
	GetAffiliateBonus(context.Context, *GetAffiliateBonusRequest) (*GetBonusResponse, error)
	GetAffiliateWithBonus(context.Context, *AffiliateBonusRequest) (*CommonResponseObj, error)
	CheckCashBackBonus(context.Context, *GetBonusRequest) (*CommonResponseObj, error)
	GetAllAwardedBonus(context.Context, *GetAllBonusRequest) (*CommonResponseObj, error)
	GetBonusWithPromoCode(context.Context, *GetBonusWithPromoCodeRequest) (*CommonResponseObj, error)
	DeleteBonus(context.Context, *DeleteBonusRequest) (*BonusResponse, error)
	GetUserBonus(context.Context, *GetUserBonusRequest) (*GetUserBonusResponse, error)
	AwardBonus(context.Context, *AwardBonusRequest) (*UserBonusResponse, error)
	AssignAffiliateBonus(context.Context, *AssignBonusRequest) (*CommonResponseObj, error)
	DeactivateUserBonus(context.Context, *BonusRequest) (*CommonResponseObj, error)
	PlaceBonusBet(context.Context, *UserBet) (*PlaceBetResponse, error)
	UpdateBonusStatus(context.Context, *BonusStatusRequest) (*CreateBonusResponse, error)
	CreateCampaignBonus(context.Context, *CreateCampaignBonusDto) (*CreateBonusResponse, error)
	UpdateCampaignBonus(context.Context, *UpdateCampaignBonusDto) (*CreateBonusResponse, error)
	DeleteCampaignBonus(context.Context, *DeleteBonusRequest) (*CreateBonusResponse, error)
	RedeemCampaignBonus(context.Context, *RedeemCampaignBonusDto) (*CreateBonusResponse, error)
	GetCampaignBonus(context.Context, *GetBonusByClientID) (*AllCampaignBonus, error)
	DeletePlayerData(context.Context, *GetBonusRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedBonusServiceServer()
}

// UnimplementedBonusServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBonusServiceServer struct {
}

func (UnimplementedBonusServiceServer) FetchBonusReport(context.Context, *FetchReportRequest) (*FetchReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchBonusReport not implemented")
}
func (UnimplementedBonusServiceServer) CreateBonus(context.Context, *CreateBonusRequest) (*CreateBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBonus not implemented")
}
func (UnimplementedBonusServiceServer) UpdateBonus(context.Context, *CreateBonusRequest) (*CreateBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBonus not implemented")
}
func (UnimplementedBonusServiceServer) GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaign not implemented")
}
func (UnimplementedBonusServiceServer) ValidateBetSelections(context.Context, *UserBet) (*ValidateBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateBetSelections not implemented")
}
func (UnimplementedBonusServiceServer) CheckDepositBonus(context.Context, *CheckDepositBonusRequest) (*CheckDepositBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDepositBonus not implemented")
}
func (UnimplementedBonusServiceServer) CheckRegisterBonus(context.Context, *GetBonusRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRegisterBonus not implemented")
}
func (UnimplementedBonusServiceServer) CheckAffiliateRegisterBonus(context.Context, *GetBonusRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAffiliateRegisterBonus not implemented")
}
func (UnimplementedBonusServiceServer) SettleBet(context.Context, *SettleBetRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleBet not implemented")
}
func (UnimplementedBonusServiceServer) SearchBonus(context.Context, *GetBonusByClientID) (*SearchBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBonus not implemented")
}
func (UnimplementedBonusServiceServer) GetActiveUserBonus(context.Context, *CheckDepositBonusRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveUserBonus not implemented")
}
func (UnimplementedBonusServiceServer) SaveAccaBonus(context.Context, *SaveAccaBonusRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveAccaBonus not implemented")
}
func (UnimplementedBonusServiceServer) GetAccaBonuses(context.Context, *GetAllBonusRequest) (*CommonResponseArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccaBonuses not implemented")
}
func (UnimplementedBonusServiceServer) GetBonus(context.Context, *GetBonusRequest) (*GetBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBonus not implemented")
}
func (UnimplementedBonusServiceServer) GetAffiliateBonus(context.Context, *GetAffiliateBonusRequest) (*GetBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAffiliateBonus not implemented")
}
func (UnimplementedBonusServiceServer) GetAffiliateWithBonus(context.Context, *AffiliateBonusRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAffiliateWithBonus not implemented")
}
func (UnimplementedBonusServiceServer) CheckCashBackBonus(context.Context, *GetBonusRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCashBackBonus not implemented")
}
func (UnimplementedBonusServiceServer) GetAllAwardedBonus(context.Context, *GetAllBonusRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllAwardedBonus not implemented")
}
func (UnimplementedBonusServiceServer) GetBonusWithPromoCode(context.Context, *GetBonusWithPromoCodeRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBonusWithPromoCode not implemented")
}
func (UnimplementedBonusServiceServer) DeleteBonus(context.Context, *DeleteBonusRequest) (*BonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBonus not implemented")
}
func (UnimplementedBonusServiceServer) GetUserBonus(context.Context, *GetUserBonusRequest) (*GetUserBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBonus not implemented")
}
func (UnimplementedBonusServiceServer) AwardBonus(context.Context, *AwardBonusRequest) (*UserBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AwardBonus not implemented")
}
func (UnimplementedBonusServiceServer) AssignAffiliateBonus(context.Context, *AssignBonusRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignAffiliateBonus not implemented")
}
func (UnimplementedBonusServiceServer) DeactivateUserBonus(context.Context, *BonusRequest) (*CommonResponseObj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateUserBonus not implemented")
}
func (UnimplementedBonusServiceServer) PlaceBonusBet(context.Context, *UserBet) (*PlaceBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceBonusBet not implemented")
}
func (UnimplementedBonusServiceServer) UpdateBonusStatus(context.Context, *BonusStatusRequest) (*CreateBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBonusStatus not implemented")
}
func (UnimplementedBonusServiceServer) CreateCampaignBonus(context.Context, *CreateCampaignBonusDto) (*CreateBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaignBonus not implemented")
}
func (UnimplementedBonusServiceServer) UpdateCampaignBonus(context.Context, *UpdateCampaignBonusDto) (*CreateBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCampaignBonus not implemented")
}
func (UnimplementedBonusServiceServer) DeleteCampaignBonus(context.Context, *DeleteBonusRequest) (*CreateBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCampaignBonus not implemented")
}
func (UnimplementedBonusServiceServer) RedeemCampaignBonus(context.Context, *RedeemCampaignBonusDto) (*CreateBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedeemCampaignBonus not implemented")
}
func (UnimplementedBonusServiceServer) GetCampaignBonus(context.Context, *GetBonusByClientID) (*AllCampaignBonus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaignBonus not implemented")
}
func (UnimplementedBonusServiceServer) DeletePlayerData(context.Context, *GetBonusRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlayerData not implemented")
}
func (UnimplementedBonusServiceServer) mustEmbedUnimplementedBonusServiceServer() {}

// UnsafeBonusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BonusServiceServer will
// result in compilation errors.
type UnsafeBonusServiceServer interface {
	mustEmbedUnimplementedBonusServiceServer()
}

func RegisterBonusServiceServer(s grpc.ServiceRegistrar, srv BonusServiceServer) {
	s.RegisterService(&BonusService_ServiceDesc, srv)
}

func _BonusService_FetchBonusReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).FetchBonusReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/fetchBonusReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).FetchBonusReport(ctx, req.(*FetchReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_CreateBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).CreateBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/CreateBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).CreateBonus(ctx, req.(*CreateBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_UpdateBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).UpdateBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/UpdateBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).UpdateBonus(ctx, req.(*CreateBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/GetCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetCampaign(ctx, req.(*GetCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_ValidateBetSelections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).ValidateBetSelections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/ValidateBetSelections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).ValidateBetSelections(ctx, req.(*UserBet))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_CheckDepositBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDepositBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).CheckDepositBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/CheckDepositBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).CheckDepositBonus(ctx, req.(*CheckDepositBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_CheckRegisterBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).CheckRegisterBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/CheckRegisterBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).CheckRegisterBonus(ctx, req.(*GetBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_CheckAffiliateRegisterBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).CheckAffiliateRegisterBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/CheckAffiliateRegisterBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).CheckAffiliateRegisterBonus(ctx, req.(*GetBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_SettleBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).SettleBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/SettleBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).SettleBet(ctx, req.(*SettleBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_SearchBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBonusByClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).SearchBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/SearchBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).SearchBonus(ctx, req.(*GetBonusByClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_GetActiveUserBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDepositBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetActiveUserBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/GetActiveUserBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetActiveUserBonus(ctx, req.(*CheckDepositBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_SaveAccaBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAccaBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).SaveAccaBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/SaveAccaBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).SaveAccaBonus(ctx, req.(*SaveAccaBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_GetAccaBonuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetAccaBonuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/GetAccaBonuses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetAccaBonuses(ctx, req.(*GetAllBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_GetBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/GetBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetBonus(ctx, req.(*GetBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_GetAffiliateBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAffiliateBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetAffiliateBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/GetAffiliateBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetAffiliateBonus(ctx, req.(*GetAffiliateBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_GetAffiliateWithBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AffiliateBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetAffiliateWithBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/GetAffiliateWithBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetAffiliateWithBonus(ctx, req.(*AffiliateBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_CheckCashBackBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).CheckCashBackBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/CheckCashBackBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).CheckCashBackBonus(ctx, req.(*GetBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_GetAllAwardedBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetAllAwardedBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/GetAllAwardedBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetAllAwardedBonus(ctx, req.(*GetAllBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_GetBonusWithPromoCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBonusWithPromoCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetBonusWithPromoCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/GetBonusWithPromoCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetBonusWithPromoCode(ctx, req.(*GetBonusWithPromoCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_DeleteBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).DeleteBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/DeleteBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).DeleteBonus(ctx, req.(*DeleteBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_GetUserBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetUserBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/GetUserBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetUserBonus(ctx, req.(*GetUserBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_AwardBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AwardBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).AwardBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/AwardBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).AwardBonus(ctx, req.(*AwardBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_AssignAffiliateBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).AssignAffiliateBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/AssignAffiliateBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).AssignAffiliateBonus(ctx, req.(*AssignBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_DeactivateUserBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).DeactivateUserBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/DeactivateUserBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).DeactivateUserBonus(ctx, req.(*BonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_PlaceBonusBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).PlaceBonusBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/PlaceBonusBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).PlaceBonusBet(ctx, req.(*UserBet))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_UpdateBonusStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BonusStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).UpdateBonusStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/UpdateBonusStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).UpdateBonusStatus(ctx, req.(*BonusStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_CreateCampaignBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignBonusDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).CreateCampaignBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/CreateCampaignBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).CreateCampaignBonus(ctx, req.(*CreateCampaignBonusDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_UpdateCampaignBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCampaignBonusDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).UpdateCampaignBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/UpdateCampaignBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).UpdateCampaignBonus(ctx, req.(*UpdateCampaignBonusDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_DeleteCampaignBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).DeleteCampaignBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/DeleteCampaignBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).DeleteCampaignBonus(ctx, req.(*DeleteBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_RedeemCampaignBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemCampaignBonusDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).RedeemCampaignBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/RedeemCampaignBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).RedeemCampaignBonus(ctx, req.(*RedeemCampaignBonusDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_GetCampaignBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBonusByClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetCampaignBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/GetCampaignBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetCampaignBonus(ctx, req.(*GetBonusByClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_DeletePlayerData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).DeletePlayerData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bonus.BonusService/DeletePlayerData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).DeletePlayerData(ctx, req.(*GetBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BonusService_ServiceDesc is the grpc.ServiceDesc for BonusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BonusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bonus.BonusService",
	HandlerType: (*BonusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "fetchBonusReport",
			Handler:    _BonusService_FetchBonusReport_Handler,
		},
		{
			MethodName: "CreateBonus",
			Handler:    _BonusService_CreateBonus_Handler,
		},
		{
			MethodName: "UpdateBonus",
			Handler:    _BonusService_UpdateBonus_Handler,
		},
		{
			MethodName: "GetCampaign",
			Handler:    _BonusService_GetCampaign_Handler,
		},
		{
			MethodName: "ValidateBetSelections",
			Handler:    _BonusService_ValidateBetSelections_Handler,
		},
		{
			MethodName: "CheckDepositBonus",
			Handler:    _BonusService_CheckDepositBonus_Handler,
		},
		{
			MethodName: "CheckRegisterBonus",
			Handler:    _BonusService_CheckRegisterBonus_Handler,
		},
		{
			MethodName: "CheckAffiliateRegisterBonus",
			Handler:    _BonusService_CheckAffiliateRegisterBonus_Handler,
		},
		{
			MethodName: "SettleBet",
			Handler:    _BonusService_SettleBet_Handler,
		},
		{
			MethodName: "SearchBonus",
			Handler:    _BonusService_SearchBonus_Handler,
		},
		{
			MethodName: "GetActiveUserBonus",
			Handler:    _BonusService_GetActiveUserBonus_Handler,
		},
		{
			MethodName: "SaveAccaBonus",
			Handler:    _BonusService_SaveAccaBonus_Handler,
		},
		{
			MethodName: "GetAccaBonuses",
			Handler:    _BonusService_GetAccaBonuses_Handler,
		},
		{
			MethodName: "GetBonus",
			Handler:    _BonusService_GetBonus_Handler,
		},
		{
			MethodName: "GetAffiliateBonus",
			Handler:    _BonusService_GetAffiliateBonus_Handler,
		},
		{
			MethodName: "GetAffiliateWithBonus",
			Handler:    _BonusService_GetAffiliateWithBonus_Handler,
		},
		{
			MethodName: "CheckCashBackBonus",
			Handler:    _BonusService_CheckCashBackBonus_Handler,
		},
		{
			MethodName: "GetAllAwardedBonus",
			Handler:    _BonusService_GetAllAwardedBonus_Handler,
		},
		{
			MethodName: "GetBonusWithPromoCode",
			Handler:    _BonusService_GetBonusWithPromoCode_Handler,
		},
		{
			MethodName: "DeleteBonus",
			Handler:    _BonusService_DeleteBonus_Handler,
		},
		{
			MethodName: "GetUserBonus",
			Handler:    _BonusService_GetUserBonus_Handler,
		},
		{
			MethodName: "AwardBonus",
			Handler:    _BonusService_AwardBonus_Handler,
		},
		{
			MethodName: "AssignAffiliateBonus",
			Handler:    _BonusService_AssignAffiliateBonus_Handler,
		},
		{
			MethodName: "DeactivateUserBonus",
			Handler:    _BonusService_DeactivateUserBonus_Handler,
		},
		{
			MethodName: "PlaceBonusBet",
			Handler:    _BonusService_PlaceBonusBet_Handler,
		},
		{
			MethodName: "UpdateBonusStatus",
			Handler:    _BonusService_UpdateBonusStatus_Handler,
		},
		{
			MethodName: "CreateCampaignBonus",
			Handler:    _BonusService_CreateCampaignBonus_Handler,
		},
		{
			MethodName: "UpdateCampaignBonus",
			Handler:    _BonusService_UpdateCampaignBonus_Handler,
		},
		{
			MethodName: "DeleteCampaignBonus",
			Handler:    _BonusService_DeleteCampaignBonus_Handler,
		},
		{
			MethodName: "RedeemCampaignBonus",
			Handler:    _BonusService_RedeemCampaignBonus_Handler,
		},
		{
			MethodName: "GetCampaignBonus",
			Handler:    _BonusService_GetCampaignBonus_Handler,
		},
		{
			MethodName: "DeletePlayerData",
			Handler:    _BonusService_DeletePlayerData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bonus.proto",
}
